- setup.cfg
- src/stdatamodels/fits_support.py
- src/stdatamodels/model_base.py
- src/stdatamodels/properties.py
- src/stdatamodels/validate.py
- tests/conftest.py
- tests/models.py
- tests/schemas/basic_model.yaml
- tests/schemas/core_metadata.yaml
- tests/schemas/fits_required_model.yaml
- tests/schemas/required_model.yaml
- tests/schemas/validation_model.yaml
- tests/test_validation.py
- tox.ini
This adds new tests for the validation features of DataModel, and makes the following changes:
- Make attribute updates respond to pass_invalid_values
- Remove unreachable code in validate.py relating to type validation
- Remove unnecessary call to custom_tree_to_tagged_tree
The testing exposed some bugs/missing features that I'll open issues for:
- Validation on read does not occur for ASDF files
- Validation on write does not occur for ASDF files
- The JSON Schema `required` property is ignored
> Add test coverage of validation code

- src/stdatamodels/model_base.py
This solves an issue we are seeing in the `jwst.datamodels` subclass of `DataModel` where the `_asdf` attribute doesn't exist due to some changes made here in `stdatamodels`
https://github.com/spacetelescope/stdatamodels/pull/4/files#diff-28744f508b621b779032bc4f0f0542d33778e66674941ec524d213cea968c24eR21
where `ctx._asdf` doesn't exist yet when needed in reading a FITS file.
```
$ pytest jwst/datamodels/tests/test_models.py::test_subarray
========================================================================== test session starts ===========================================================================
platform darwin -- Python 3.8.5, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /Users/jdavies/dev/jwst, configfile: setup.cfg
plugins: asdf-2.7.1, requests-mock-1.8.0, …
```
> Initialize DataModel._asdf early in __init__()

- src/stdatamodels/fits_support.py
- src/stdatamodels/util.py
- tests/test_util.py
We commented this code out originally because jwst model classes aren't available in stdatamodels.  In this PR it's revived, but compares model classes by their string names so that jwst models aren't required.
> Compare model type as string when verifying FITS hash

- src/stdatamodels/validate.py
This PR reverts the change in this repo that enabled the ASDF ndarray validators.  It turns out those aren't compatible with some of the jwst table schemas, which include columns with nested arrays that aren't yet supported by ASDF.
We're just going to keep using the ndarray validation in `properties._cast` for now, and switch to asdf built-in validators once they support all the jwst use cases.
> Don't use ASDF ndarray validators for now

- tests/test_fits.py
- tests/test_history.py
- tests/test_schema.py
@jdavies-st pointed out that the test_history.py tests are passing now.  I checked the other skipped tests and found a few more.
> Enable tests that have started passing due to FITS hash fix

- .gitignore
- .readthedocs.yml
- .travis.yml
- docs/Makefile
- docs/source/api.rst
- docs/source/conf.py
- docs/source/index.rst
- pyproject.toml
- setup.cfg
- setup.py
- src/stdatamodels/__init__.py
- tox.ini
This creates a bare-bones docs directory, currently with nothing but the auto-generated API documentation for `DataModel`.  I looked into migrating documentation over from jwst but what's there is very jwst-specific and I don't have the time to rewrite it right now.
> Initialize documentation

- tests/conftest.py
- tests/models.py
- tests/schemas/anyof_model.yaml
- tests/schemas/basic_model.yaml
- tests/schemas/core_metadata.yaml
- tests/schemas/fits_required_model.yaml
- tests/schemas/required_model.yaml
- tests/schemas/validation_model.yaml
- tests/test_fits.py
- tests/test_models.py
This PR updates test_models.py to use non-jwst models defined in the tests directory.  It also moves FITS-related tests to test_fits.py (I'm planning to isolate the FITS stuff as much as possible).
~~Includes commits from #4 so best to wait to review this until that one is merged (or review only the latest commit).~~
> Update tests in test_models.py

- src/stdatamodels/model_base.py
- tests/conftest.py
- tests/models.py
- tests/schemas/anyof_model.yaml
- tests/schemas/basic_model.yaml
- tests/schemas/core_metadata.yaml
- tests/schemas/fits_required_model.yaml
- tests/schemas/required_model.yaml
- tests/schemas/validation_model.yaml
- tests/test_fits.py
- tests/test_models.py
The only relevant change turned out to be support for asdf 2.8's change of opinion on null values.  There was also a logging function added to model_base.py, but its use was commented out and is seemingly only to be enabled when debugging, which doesn't work well now that this code is in one of jwst's dependencies.
Branched off of #10.  Resolves #3
> Catch up to latest jwst master

- src/stdatamodels/model_base.py
- tests/test_models.py
I don't know if we'll keep `DataModel.__del__` long term, but this will make it safer in the meantime.
> Make close() resistant to partially initialized models

- tests/models.py
- tests/schemas/fits_model.yaml
- tests/schemas/table_model.yaml
- tests/schemas/transform_model.yaml
- tests/test_fits.py
- tests/test_schema.py
These tests were:
- Updated to use test models defined in this package
- Removed if they were only relevant to jwst, or if they duplicated coverage in test_validation.py and test_util.py
- Moved to test_fits.py (the final frontier) if they didn't really belong in test_schema.py
> Update tests in test_schema.py

- setup.cfg
- tests/conftest.py
- tests/test_filetype.py
- tests/test_history.py
- tests/test_s3_utils.py
- tests/test_schema.py
- tests/test_validation.py
- tox.ini
Now that all the tests are passing or appropriately xfail'ed, we can have flake8 check the tests directory.
> Enable flake8 on the tests directory and resolve issues

- .travis.yml
- tox.ini
This adds 2 new `allow_failures` jobs to the Travis matrix that run the `jwst.datamodels` and `romancal.datamodels` tests.  This will give us a heads-up if anything in an `stdatamodels` PRs breaks something in the dev versions of those 2 packages.
Only running the `.datamodels` tests now for each package for efficiency.  And running on the installed versions of the packages.
Also added a Python 3.9 job.
Resolves #34
> Add jwst and romancal jobs to CI

- src/stdatamodels/model_base.py
- src/stdatamodels/util.py
- src/stdatamodels/validate.py
- tests/test_validation.py
This fixes validation behavior when an object with nested None values is assigned to a DataModel.
Resolves spacetelescope/jwst#5491
> Remove nested None values before validating

- CHANGES.rst
- src/stdatamodels/fits_support.py
- tests/test_fits.py
This function is used in MiriTE, so I removed the underscore from its name and added a test.
> Make is_builtin_fits_keyword a public function

- .github/workflows/publish-to-pypi.yml
This will enable Github actions to build and publish the `stdatamodels` package to PyPI when a Github release is created in this repository for a new or existing semver-compliant tag.
Further information may be found here:
https://github.com/spacetelescope/action-publish_to_pypi
> Enable Pypi publication service

- CHANGES.rst
- src/stdatamodels/model_base.py
- tests/test_models.py
- tests/test_schema.py
This removes automatic mangement of the meta.date attribute from this package and introduces an on_init hook that will let us re-implement the feature in jwst and romancal.
Here's what the updates to jwst will look like:
https://github.com/spacetelescope/jwst/compare/master...eslavich:AL-420-implement-meta-date-management
And for romancal:
https://github.com/spacetelescope/romancal/compare/main...eslavich:AL-420-meta-date-management
> Remove automatic management of meta.date and introduce on_init hook

- src/stdatamodels/model_base.py
These two methods are needed by stpipe.  I thought we'd better add them here as a guide for anyone who needs to implement a DataModel subclass in the future.
Resolves #56
> Add CRDS method implementations to be DataModel class

- CHANGES.rst
- src/stdatamodels/model_base.py
- tests/test_schema.py
The `asdf.tags.core.NDArrayType` class does not actually subclass `np.ndarray`, so DataModel wasn't removing them when it should have been.
Resolves #55
> Recognize asdf.tags.core.NDArrayType as an array

- CHANGES.rst
- setup.cfg
- src/stdatamodels/model_base.py
- tests/test_resources.py
This is a riff on https://github.com/spacetelescope/stdatamodels/pull/54 that I think will give us a little more flexibility in the future.  I also added parameterized the tests to cover models opened from ASDF files.
> Improve management of open files among shallow DataModel copies

- src/stdatamodels/model_base.py
- tests/test_resources.py
A bug revealed by tests in jwst...
> Handle multiple calls to DataModel.close gracefully

- src/stdatamodels/fits_support.py
- src/stdatamodels/properties.py
I can't think of why we'd want logger levels set to DEBUG in a library package, but let me know if there's something I'm overlooking.
https://jira.stsci.edu/browse/AL-473
> Don't set level on library loggers

- CHANGES.rst
- src/stdatamodels/fits_support.py
- tests/test_fits.py
This is a fix for https://github.com/spacetelescope/jwst/issues/6104.
I think I understand the full story now --  asdf is trying to write the groupdq array into a block because of this change (released in asdf 2.7.4):
https://github.com/asdf-format/asdf/pull/949
Since RefPixStep is assigning groupdq to a view of itself:
https://github.com/spacetelescope/jwst/blob/1.2.2/jwst/refpix/irs2_subtract_reference.py#L251
it ends up with a base array with a wacky strides value that asdf doesn't know how to compute a view against, so it's forced to make a copy.  Before 2.7.4 asdf did not make a copy but that left the door open to other problems.
In the end I think the sanest thing we can do here is make the arrays C-contiguous before saving to an ASDF-in-FITS file, since that is how astropy.io.fits …
> Make arrays C-contiguous on save

- CHANGES.rst
- src/stdatamodels/fits_support.py
- src/stdatamodels/model_base.py
- tests/models.py
- tests/test_fits.py
This fixes a bug seen when reading in old CRDS reffiles and trying to write them back out.
Resolves [AL-556](https://jira.stsci.edu/browse/AL-556)
Resolves spacetelescope/jwst#6028 / [JP-2080](https://jira.stsci.edu/browse/JP-2080)
- Don't allow ASDF hdus to get passed through `extra_fits`, ever
- Never write out any ASDF extension if `self._no_asdf_extension=True`
> Fix _no_asdf_extension bug

- src/stdatamodels/fits_support.py
- src/stdatamodels/model_base.py
- src/stdatamodels/util.py
- src/stdatamodels/validate.py
- tests/schemas/table_model.yaml
- tests/test_fits.py
- tests/test_schema.py
- tests/test_util.py
- tests/test_validation.py
This PR adds two keyword arguments to the DataModel initializer -- `cast_fits_arrays`, which controls the cast to schema dtype that occurs by default when reading an array from a FITS file, and `validate_arrays`, which enables full validation of the schema datatype, ndim, and/or max_ndim.
These options will be used by CRDS to impose strict validation on arrays for submitted reference files.
> Add options for strict validation of arrays

- src/stdatamodels/util.py
- tests/test_util.py
This PR changes the datamodels casting to raise an error when asked to cast a FITS binary table with a pseudo-unsigned integer column.  Due to a bug in astropy `np.asanyarray` causes the TZEROn offset to be applied twice, which makes a mess of the unsigned integer data in the column.
The miri flat references in the current context all have this problem and will need to be fixed and re-submitted to prevent this exception from occurring.
> Raise error when asked to cast FITS binary table with pseudo-unsigned column

- CHANGES.rst
- src/stdatamodels/util.py
- tests/test_util.py
Previously we raised an exception when asked to cast a FITS_rec with an unsigned integer column, since that hits a bug in astropy that garbles the data in the column by applying the bzero shift twice.  This PR adds special handling for such arrays so that we no longer need to raise the exception.
> Support casting of FITS_rec with unsigned integer column

- CHANGES.rst
- src/stdatamodels/fits_support.py
Resolves JP-2227
Closes issue: https://github.com/spacetelescope/jwst/issues/6271
To support lazy loading in JWST data models a wrapper is used to wrap Numpy `ndarrays` called NDArrayType.  At the lower levels in the class hierarchy this causes problems during write.  When a data model is written an HDU needs to be created for the HDU list to be written out.  This can only be done properly if the `ndarray.dtype` is known.
For lazy loading this may not be known because the needed information is not in the NDArrayType wrapper, so an extra step must be taken to check if the type is NDArrayType, then ensure the `ndarray` gets loaded.  When this is done all the needed information for type checking on write is there and the round trip will succeed.
> JP-2227: Making changes to properly create HDU from an ndarray.

- CHANGES.rst
- src/stdatamodels/schema.py
Currently, jwst is failing due to issues with the additions to `transform-1.2.0` in asdf-transform-schemas development. This is due to issues with the `schemas` module in this package.
The PR spacetelescope/jwst#6752 fixes the majority of the this problem by altering how `transform-1.2.0` is used in some of the jwst datamodels; however, this does not completely fix the problem because the schema module still attempts to remove items from the tree which don't exist. This PR fixes that remaining issues.
> Portion of fix for asdf-transform-schemas develop.

- CHANGES.rst
- src/stdatamodels/fits_support.py
jsonschema 4.x does not support storing custom attributes on the validator object.
> Fix issues with FITS writing validators with jsonschema 4.x

- .github/workflows/ci.yml
Currently, [the GitHub Actions workflow job testing `jwst.datamodels`](https://github.com/spacetelescope/stdatamodels/runs/7069458676?check_suite_focus=true) fails because the requested and sync'ed CRDS context is different from the operational context on the server. This change ensures that the correct context is sync'ed on every workflow run, and caches and re-uses the current context until it changes.
**Checklist**
> fix crds context in workflow to follow operational context of server

- CHANGES.rst
- setup.cfg
- tests/test_fits.py
See asdf issue https://github.com/asdf-format/asdf/issues/1232
To summarize the issue, resaving an asdf in fits file breaks the link between hdu
items and arrays within the asdf tree. This results in inclusion of array data as
internal blocks in the asdf tree and a (sometimes substantial) increase in the size
of the tree. The test added here checks that the asdf tree stored in the 'ASDF' hdu
does not change size on a resave.
This test is currently skipped as it will fail with the current asdf version.
**Checklist**
> Add test for asdf data duplication issue with fits

- CHANGES.rst
- src/stdatamodels/properties.py
astropy 5.2 will deprecate override__dir__
The deprecation notes suggest an alternative (used here) which should work for all versions of python >=3.3
Deprecation: https://github.com/astropy/astropy/blob/0944607116f373e64e94ce3e5535c49509897c87/astropy/utils/compat/misc.py#L19
Root python issue: https://bugs.python.org/issue12166
Fixed in 3.3: https://docs.python.org/3.3/whatsnew/changelog.html
**Checklist**
> remove use of deprecated override__dir__

- CHANGES.rst
- setup.cfg
- tests/test_history.py
test_history fails if asdf-astropy is installed.
The root cause is that asdf-astropy serializes astropy.time.Time objects in a way that is incompatible with the schema for history entries in some cases (the way that it is currently being handled). If asdf-astropy is not installed, astropy.time.Time serialization will fall back to a legacy extension in astropy.io.misc.asdf which was allowing the test to pass.
In asdf-astropy 0.3.0+ the time serialization was adjusted to be history compatible but only for a limited subset of astropy.time.Time formats. This PR adjust the astropy.time.Time object so that it explicitly uses one of those formats. Moreover, it adds asdf-astropy as an explicit dependency so that stdatamodels does not accidentally fall back on the legacy astropy.io.misc.asdf …
> Bugfix for `test_history` times.

- CHANGES.rst
- src/stdatamodels/fits_support.py
- src/stdatamodels/model_base.py
- src/stdatamodels/schema.py
- tests/test_models.py
Remove the self-reference (`self._ctx = self`) and other difficult to garbage collect patterns to help python clean up when a process allocates and saves several models.
DataModel contains a self reference that makes it difficult to collect. ~~This PR clears that reference on __del__.~~ This PR changes _ctx to a property.
The use of `validate` to generate the hdulist suffers from leakage as validators are cached resulting in references to the hdulist remaining after a model deleted. This PR changes the hdulist ref to a weakref in FitsContext to work around the caching.
walk_schema defines a recursive function (recurse) that can capture references to data when called from _load_from_schema. This PR adds an explicit del of the recurse function to help it clean up after use.
~~These are only …
> Resolves JP-2798 improves memory usage of datamodel

- .github/workflows/ci.yml
- CHANGES.rst
- setup.cfg
- tox.ini
In an attempt to standardize CI across repos and make it less confusing, this PR reintroduces `tox` and uses the `toxenv` naming scheme from the Romancal repo.
Additionally, `toxenvs` in the `check` matrix run concurrently with other tests.
**Checklist**
> refactor CI and use `tox.ini` with Tox 4 and PEP517 build

- CHANGES.rst
- setup.cfg
- src/stdatamodels/fits_support.py
- src/stdatamodels/model_base.py
- tests/test_embedded_asdf.py
- tests/test_fits.py
This PR reimplements support for ASDF-in-FITS in this package.  ~~It requires https://github.com/asdf-format/asdf/pull/1289, so we'll need to get that merged and released before merging this.~~
**Checklist**
> Reimplement support for ASDF-in-FITS in this package

- README.md
- src/stdatamodels/jwst/datamodels/tests/test_schema_against_crds.py
~~#112 introduced a few tests to access CRDS. These expect a CRDS_PATH environment variable and can take considerable time to download data.~~
~~This PR modifies the log line accessing CRDS_PATH (to fall back to a value of None if CRDS_PATH is not defined) and adds a pytest mark (off by default) that controls running of the crds tests. The tox tests are modified to enable this new crds mark.~~
~~Edited: This PR adds a no_crds pytest option to disable tests that require downloading 500MB of files and~~ addresses a few failures related to local testing that resulted in test failures when:
- not run on the vpn (or on the vpn but without a defined CRDS_PATH environment variable)
- not run on a machine with a pre-existing cached CRDS context
~~A description of the mark is added to the …
> fixes to run tests outside of CI

- tox.ini
During migration of datamodels from jwst to this package, testing was switched to a different JWST branch:
https://github.com/spacetelescope/stdatamodels/pull/112
that was compatible with the move.
The switch back after the move finished
https://github.com/spacetelescope/stdatamodels/commit/46e96286d7c23eaf7bed5f1baa1b441f470dacee
changed the CI to test against the released jwst version instead of the development version.
Here is one example of the issue (where jwst 1.9.4 was installed instead of the current git head)
https://github.com/spacetelescope/stdatamodels/actions/runs/4280618786/jobs/7458972540#step:12:59
This PR switches the jwst ci testing to be against the current default git branch.
Closes #
This PR addresses ...
**Checklist**
> test against jwst developement version instead of released version

- src/stdatamodels/jwst/transforms/converters/tests/test_models.py
Resolves [JP-nnnn](https://jira.stsci.edu/browse/JP-nnnn)
Closes #
Importing from another package's tests is strictly frowned upon as the tests are considered part of the private interface of the package. `asdf-astropy` is moving some stuff in its tests in astropy/asdf-astropy#170, which `stdatamodels` is importing in its tests. To be nice `asdf-astropy` is including a deprecation warning, which still causes one of the `stdatamodels` tests to fail see: https://github.com/astropy/asdf-astropy/actions/runs/4265199400/jobs/7424250651. This PR fixes that issue before it can arise.
**Checklist**
> Prevent deprecation issue from importing from tests

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/dqflags.py
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
Partially resolves [JP-3015](https://jira.stsci.edu/browse/JP-3015)
Updated the jwst dqflags definitions and core schema to support the new jwst undersampling_correction step. This includes a new DQ flag definition and a step status keyword.
**Checklist**
> JP-3015: Updates to support new JWST undersampling_correction step

- pyproject.toml
- tox.ini
The coverage measurement does not appear to be working correctly.
For example, this function:
https://github.com/spacetelescope/stdatamodels/blob/dc0da6d55da8e6251ef04b55551d14246c488a48/src/stdatamodels/asdf_in_fits.py#L13
is covered by this test:
https://github.com/spacetelescope/stdatamodels/blob/dc0da6d55da8e6251ef04b55551d14246c488a48/tests/test_asdf_in_fits.py#L35
The test does appear to be running (confirmed locally) and coverage reports run locally outside tox (with a development install of the package) show increased coverage.
However this function does not appear to have coverage in the CI.
https://app.codecov.io/gh/spacetelescope/stdatamodels/blob/master/src/stdatamodels/asdf_in_fits.py
I tested a few of the solutions mentioned here, which describe how pytest will test the …
> fix coverage measurement

- CHANGES.rst
- pyproject.toml
- src/stdatamodels/basic_utils.py
- src/stdatamodels/dqflags.py
- src/stdatamodels/dynamicdq.py
- src/stdatamodels/jwst/datamodels/dark.py
- src/stdatamodels/jwst/datamodels/darkMIRI.py
- src/stdatamodels/jwst/datamodels/flat.py
- src/stdatamodels/jwst/datamodels/fringe.py
- src/stdatamodels/jwst/datamodels/lastframe.py
- src/stdatamodels/jwst/datamodels/linearity.py
- src/stdatamodels/jwst/datamodels/mask.py
- src/stdatamodels/jwst/datamodels/nirspec_flat.py
- src/stdatamodels/jwst/datamodels/persat.py
- src/stdatamodels/jwst/datamodels/photom.py
- src/stdatamodels/jwst/datamodels/reference.py
- src/stdatamodels/jwst/datamodels/reset.py
- src/stdatamodels/jwst/datamodels/saturation.py
- src/stdatamodels/jwst/datamodels/superbias.py
- src/stdatamodels/jwst/datamodels/trapdensity.py
- src/stdatamodels/jwst/datamodels/wfssbkg.py
- tests/test_dq.py
Resolves [JP-3110](https://jira.stsci.edu/browse/JP-3110)
This PR moves:
- `stcal.dqflags`
- `stcal.dynamicdq`
- `stcal.basic_utils`
To `stdatamodels`. These modules appear to only be used by `jwst`.
This is to facilitate making `stdatamodels` independent of the JWST pipeline code, so that users of `jwst` pipeline products can open those products using tools like `jdaviz` without having to install the entire JWST pipeline. Instead, `stdatamodels` contains all the necessary code to unpack the asdf-in-fits objects embedded in some jwst pipeline products.
Fixes #133
**Checklist**
> JP-3110 Move `dqflags` and related from `stcal` to `stdatamodels`

- CHANGES.rst
- docs/source/asdf_in_fits.rst
- src/stdatamodels/asdf_in_fits.py
- tests/test_asdf_in_fits.py
Add support for reading ASDF data from an already opened HDUList.
Fixes #135 
Also fixes sphinx link in docs that was in #122
**Checklist**
> add HDUList support to asdf_in_fits.open

- src/stdatamodels/fits_support.py
- src/stdatamodels/jwst/datamodels/multiexposure.py
- src/stdatamodels/jwst/datamodels/schema_editor.py
asdf.resolver will be deprecated in 2.15: https://github.com/asdf-format/asdf/pull/1362
A few uses were found in stdatamodels
1) fits_support adds a resolver for a non-existent path: https://github.com/spacetelescope/stdatamodels/blob/740477cfc3c5540233de5606e4da23241abc4266/src/stdatamodels/fits_support.py#L362-L366
2) jwst/datamodels/multiexposure provides resolvers that are equivalent to the defaults https://github.com/spacetelescope/stdatamodels/blob/740477cfc3c5540233de5606e4da23241abc4266/src/stdatamodels/jwst/datamodels/multiexposure.py#L89-L98
3) jwst/datamodels/schema_editor uses the default resolver to resolve schema references https://github.com/spacetelescope/stdatamodels/blob/740477cfc3c5540233de5606e4da23241abc4266/src/stdatamodels/jwst/datamodels/schema_editor.py#L397-L415 …
> remove uses of deprecated asdf.resolver

- docs/source/conf.py
`tomli` is implemented read-only as `tomllib` in Python 3.11
**Checklist**
> import `tomli` as `tomllib` for `docs` builds before Python 3.11

- src/stdatamodels/jwst/datamodels/reference.py
Changes to `ReferenceFileModel.save` introduced in #132 cause the following jwst doc test to fail:
https://github.com/spacetelescope/jwst/blob/master/docs/jwst/assign_wcs/asdf-howto.rst#create-the-reference-file
The failure can be seen [in this regression test run result](https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-devdeps/644/testReport/junit/docs.jwst.assign_wcs.asdf-howto/rst/_unstable_deps__asdf_howto_rst/)
The doctest expects that `ReferenceFileModel.save` will return the `output_filename` (behavior inherited from `DataModel`):
https://github.com/spacetelescope/stdatamodels/blob/4c177d50096bf4702b021239500937f1db47a488/src/stdatamodels/model_base.py#L536
This PR updates `ReferenceFileModel.save` to return the `output_filename` to fix the failing jwst doc test.
> fix reference save return value

- .github/workflows/ci_cron.yml
These changes move the majority of MacOS jobs to the weekly scheduled workflow. This should alleviate the issue where the limited MacOS runners for the organization are not available for CI jobs.
**Checklist**
> move MacOS jobs to schedule

- CHANGES.rst
- pyproject.toml
`pytest-openfiles` has been deprecated and is interfering with the use of fixtures in our test code (ones that handle files). This PR switches `ResourceWarnings` into errors which will catch almost all cases of files left open. The only cases it does not catch is if an open file handle is assigned to a global variable as the "warning" will not be emitted until python stops running, which occurs after pytest has completed.
Similar to spacetelescope/romancal#666
**Checklist**
> Remove `pytest-openfiles`

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/dqflags.py
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
Resolves [JP-3005](https://jira.stsci.edu/browse/JP-3005)
Closes #
This PR adds the cal_step keyword to denote whether pixel replacement was run, skipped, etc. It appears that I don't have many permissions here, as I can't add milestones/labels or request reviewers.
**Checklist**
> JP-3005: Update core schema for new step status keyword in metadata

- CHANGES.rst
- pyproject.toml
- src/stdatamodels/fits_support.py
- src/stdatamodels/jwst/datamodels/tests/test_models.py
- src/stdatamodels/jwst/datamodels/util.py
`pytest-openfiles` was not catching all the open file-handles left during the tests. These handles were often blocked by
other exception handling. The removal of `pytest-openfiles` and replacement with `ResourceWarning` catching pointed this issue out in the form of `PytestUnraisableExceptionWarning`s, because other exceptions were being caught `pytest` could not raise the `ResourceWarning` as an exception.
This PR fixes all the new file handles being caught and turns `PytestUnraisableExceptionWarning`s into errors to prevent this issue in the future.
**Checklist**
> Fix open file handles which were not being caught by `pytest-openfiles`

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/specwcs_nircam_grism.schema.yaml
- src/stdatamodels/jwst/transforms/converters/jwst_models.py
- src/stdatamodels/jwst/transforms/models.py
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/nircam_grism_dispersion-1.0.0.yaml
Resolves [JP-2113](https://jira.stsci.edu/browse/JP-2113)
Closes #
This PR provides higher-order polynomial transform models for the NIRCam WFSS grisms. It has a coupled PR in jwst (https://github.com/spacetelescope/jwst/pull/7018).
**Checklist**
> JP-2113: Update NIRCam WFSS transforms for field dependence (v6)

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/ifucubepars.py
- src/stdatamodels/jwst/datamodels/schemas/nirspec_ifucubepars.schema.yaml
Is used to resolve [JP-3047](https://jira.stsci.edu/browse/JP-3047)
This PR makes updates to the NIRSpec cubepar reference file data model to read in 3 new extensions. These extensions have names of MULTICHAN_PRISM_DRIZZLE, MULTICHAN_MED_DRIZZLE, and  MULTICHAN_HIGH_DRIZZLE.
These extensions are used to build ifu cubes when weighting='drizzle'. In particular these arrays are used when the grating/filters in the association are not the same and the wavelength range will then be non-linear. For NIRSpec all the gratings need to be either all  prism, all  medium, or all high resolution (i.e no mixture of medium and high resolution gratings are allowed). 
According to the type of grating (prism, medium, or high) the wavelength array is read in from the new extensions and used when creating an …
> Update the NIRSpec Cubepar reference file to read in drizzle wavelength arrays

- CHANGES.rst
- src/stdatamodels/jwst/transforms/models.py
Related to [JP-2113](https://jira.stsci.edu/browse/JP-2113)
This PR addresses speed issues caused in part by an over-long vector used for interpolation - reducing length from 1000 -> 40 appears to improve speeds in a linear fashion wrt. vector length.
**Checklist**
> Improve backwards transform speed for NRC_WFSS

- CHANGES.rst
- src/stdatamodels/fits_support.py
- src/stdatamodels/jwst/datamodels/tests/test_models.py
- src/stdatamodels/jwst/datamodels/util.py
- src/stdatamodels/model_base.py
This PR accompanies the jwst PR:
https://github.com/spacetelescope/jwst/pull/7599
see that PR description for more details.
TLDR; address open file issues in downstream jwst CI. Note that a complete fix requires both this PR and the above jwst PR. A test PR (https://github.com/spacetelescope/jwst/pull/7601) was opened against jwst to show the expected final result (showing no `ResourceWarning` and `PytestUnraisableExceptionWarning`.
https://github.com/spacetelescope/jwst/actions/runs/5225497772/jobs/9435044814
**Checklist**
> Jwst resource warnings from failure to close open files

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/outlierpars.schema.yaml
Supports [JP-3207](https://jira.stsci.edu/browse/JP-3207)
Closes #
This PR adds another parameter to the outlier_detection parameter data model. This parameter 'ifu_second_check' is a boolean and controls if a second level of outlier detection is performed. 
**Checklist**
> added ifu_second_check to outlier detection parameter

- src/stdatamodels/jwst/datamodels/tests/test_open.py
- src/stdatamodels/jwst/datamodels/tests/test_schema_against_crds.py
I noticed a few expected `NoTypeWarning` messages in the test logs. This PR uses `pytest.warns` to catch (and check for) these warnings and modifies the import of `NoTypeWarning` in `test_schema_against_crds.py` to make sure that the issued `NoTypeWarning` class in the warning filter matches the one issued by the code (this can differ if the tests are run from the repository by the code being tested is installed).
**Checklist**
> catch expected NoTypeWarnings in tests

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/ramp.py
- src/stdatamodels/properties.py
Resolves [JP-2506](https://jira.stsci.edu/browse/JP-2506)
This PR addresses the ZEROFRAME array for the RampModel getting incorrectly allocated with dimensions (ngroups, nrows, ncols), when it should have dimensions (nints, nrows, ncols).  This RampModel array gets automatically allocated when referenced.  The dimensions for all arrays of dimension `ndim` is that it should have the dimensions `dims[-ndims:]` where `dims` is the dimensions of the primary array.  This assumption is incorrect.  There is now a special handler for the ZEROFRAME array to ensure it gets allocated with the proper dimensions.
This changed doesn't cause any CI failures in `STCAL`, `JWST`, nor `stdatamodels`.
**Checklist**
> JP-2506: Updating How the ZEROFRAME Array gets Allocated

- docs/rtd_environment.yaml
sphinx-asdf 0.2.0 fails for some uses in python 3.11 (see: https://github.com/asdf-format/sphinx-asdf/pull/72).
This PR temporarily switches the docs to build in 3.10 until an update can be released for sphinx-asdf.
**Checklist**
> build docs with python 3.10

- CHANGES.rst
- docs/source/jwst/datamodels/metadata.rst
- pyproject.toml
pyproject.toml test paths did not include the docs directory. This limited the number of doctests run during pytest runs (and the CI in this package). Downstream testing in asdf revealed this limitation and one failing doctest.
This PR adds the docs directory to the test paths and fixes the one failing doctest.
**Checklist**
> add docs to test paths, fix failing doctest

- CHANGES.rst
- src/stdatamodels/jwst/transforms/extensions.py
V23ToSkyConverter is supported in the jwst.transforms asdf extension version 0.7.0 (see [0.7.0 manifest](https://github.com/spacetelescope/stdatamodels/blob/fbd97cc7ab5a675d36e42db25218f8bffec8f494/src/stdatamodels/jwst/transforms/resources/manifests/jwst_transforms-0.7.0.yaml#L88)) but is not currently supported in 1.0.0 (see [1.0.0 manifest](https://github.com/spacetelescope/stdatamodels/blob/master/src/stdatamodels/jwst/transforms/resources/manifests/jwst_transforms-1.0.0.yaml))
This removes V23ToSkyConverter from the 1.0.0 extension (which already does not support the tag) and in all prior versions of asdf this converter was ignored.
Previously asdf ignored any Converter that lists tags that are not in the manifest. This behavior is undocumented and may conflict with future asdf …
> remove unused V23ToSkyConverter from jwst.transforms extension 1.0.0

- CHANGES.rst
- pyproject.toml
- src/stdatamodels/fits_support.py
- src/stdatamodels/jwst/datamodels/tests/test_multislit.py
- src/stdatamodels/jwst/datamodels/tests/test_validation.py
- src/stdatamodels/validate.py
- tests/test_fits.py
- tests/test_schema.py
- tests/test_validation.py
get ValidationError from asdf.exceptions
get 'type' validator from asdf.schema.YAML_VALIDATORS
Regression tests running at: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/790/
**Checklist**
> use asdf instead of jsonschema directly

- CHANGES.rst
- src/stdatamodels/dynamicdq.py
- tests/test_dynamicdq.py
This PR adds some basic unit tests for `dynamic_mask` and improves performance by removing use of `np.where` calls on binary masks and instead uses the masks directly (local testing shows the new code takes ~30% the time).
Regtest run with these changes show no errors:
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/812/pipeline/123
**Checklist**
> Add tests for dynamic_mask and remove usage of `numpy.where`

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
Resolves [JP-3329](https://jira.stsci.edu/browse/JP-3329)
Closes spacetelescope/jwst#7791
This PR adds the new "GSC_VER" keyword to the JWST core schema, to keep in synch with the changes made to the keyword dictionary in [JWSTKD-534](https://jira.stsci.edu/browse/JWSTKD-524). In addition to adding the definition of GSC_VER, it also makes minor updates to the comment/title field of several other xxx_VER keywords, again in keeping with changes made in the dictionary.
**Checklist**
> JP-3329: Add GSC_VER to JWST core schema

- pyproject.toml
- tests/test_models.py
- tox.ini
This PR cleans up the warnings in the test suite (these were almost all from use of `np.empty` which often produced values that fell outside of the range of the destination datatype when the empty arrays were assigned to a datamodel).
This PR also turns all warnings into errors in the test suite (with 1 exception where `RuntimeWarning` with a message `numpy.ndarray size changed` is ignored as it's produced by importing astropy code).
If there's any objection to turning all warnings into errors I'm happy to remove that part of this PR.
**Checklist**
> clean up some test warnings and turn warnings into errors in ci

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/gain.schema.yaml
Resolves [JP-3349](https://jira.stsci.edu/browse/JP-3349)
Closes spacetelescope/jwst#7832
Add `$ref` to `keyword_filter` schema to `gain` schema to support the `meta.instrument.filter` parameter added to the corresponding miri gain crds file.
**Checklist**
> JP-3349: add keyword_filter ref to gain.schema

- tox.ini
See: https://github.com/spacetelescope/roman_datamodels/pull/261 for more details
tox 4.9 will no longer run environments that are not either:
- prefixed with a python version: e.g. `py310` for python 3.10
- listed in `tox.ini`
This PR adds the weekly cron env `test-devdeps-xdist` to `tox.ini` so hopefully it will ~fail in a new way~ succeed next week when run with tox 4.9.
**Checklist**
> add weekly cron env to tox.ini to fix tox 4.9 compatibility

- src/stdatamodels/jwst/datamodels/tests/test_schema_against_crds.py
The fgs distortion reference file on crds: https://jwst-crds.stsci.edu/browse/jwst_fgs_distortion_0003.asdf
contains an invalid set of ASDF tags. Looking at the first few lines of the file...
```
#ASDF 1.0.0
#ASDF_STANDARD 1.2.0
%YAML 1.1
%TAG ! tag:stsci.edu:asdf/
--- !core/asdf-1.0.0
```
The file reports to be ASDF standard version 1.2.0, yet uses the `core/asdf-1.0.0` tag (which [does not exist in 1.2.0 which uses `core/asdf-1.1.0` instead](https://github.com/asdf-format/asdf-standard/blob/4e461f3a61e722bad8b4302d9bc52b6503aacbbd/src/asdf_standard/resources/schemas/stsci.edu/asdf/version_map-1.2.0.yaml#L6)). For asdf 3.0 (currently in development and soon to be released), this will result in a warning and the data associated with this tag will be loaded as a `TaggedDict` instead of an …
> add warning filter for known issue with fgs distortion file on crds

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/outlierifuoutput.schema.yaml
This PR addresses what looks like a typo, found in the outlierifuoutput schema during a comparison to the keyword dictionary (which does not have any version of this metadata yet). @jemorrison Does this look like a fix or was it the intended name?
**Checklist**
> Fix typo in ifu-outlier metadata

- .readthedocs.yaml
RTD no longer supports any system_packages setting:
https://blog.readthedocs.com/drop-support-system-packages/
This PR removes the unused system_packages setting
**Checklist**
> remove unsupported RTD system_packages setting

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
Resolves [JP-3244](https://jira.stsci.edu/browse/JP-3244)
This PR addresses issues in extraction window centering for MIRI LRS fixed slit observations. Target RA/Dec information is not necessarily accurate, and an alternative was desired. The dither offset from slit center is a known and fixed quantity - we can use this with the transforms and wcsinfo metadata to store the RA/Dec of the dither offset position for extraction centering. It must be stored rather than calculated on the fly because the WCS frames necessary for calculation from existing metadata no longer exist after the product is resampled, prior to extraction.
**Checklist**
> JP-3244: Add dither pointing RA/Dec to schema

- CHANGES.rst
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/coords-0.7.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/coords-1.0.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/grating_equation-0.7.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/gwa_to_slit-0.7.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/logical-0.7.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/miri_ab2slice-0.7.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/nircam_grism_dispersion-0.7.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/niriss_grism_dispersion-0.7.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/niriss_soss-0.7.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/refraction_index_from_prism-0.7.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/rotation_sequence-0.7.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/slit_to_msa-0.7.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/snell-0.7.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/v23tosky-0.7.0.yaml
asdf will soon warn for refs that are not uris. This PR changes the few remaining `$ref`s that contain tags to uris.
The tag `tag:stsci.edu:asdf/transform/transform-1.1.0` resolves to `http://stsci.edu/schemas/asdf/transform/transform-1.1.0`. All uses of this tag were replaced with the corresponding uri.
Resolves [JP-nnnn](https://jira.stsci.edu/browse/JP-nnnn)
Closes #
This PR addresses ...
**Checklist**
> switch schema refs that use tag to uris

- CHANGES.rst
- src/stdatamodels/fits_support.py
- src/stdatamodels/model_base.py
- src/stdatamodels/util.py
- src/stdatamodels/validate.py
Prior to asdf 3.0, `FITS_rec` (a subclass of ndarray) was serialized like an ndarray. In asdf 3.0, this will result in a warning:
```
asdf.exceptions.AsdfConversionWarning: A ndarray subclass (<class 'astropy.io.fits.fitsrec.FITS_rec'>) was converted as a ndarray. This behavior will be removed from a future version of ASDF. See https://asdf.readthedocs.io/en/latest/asdf/config.html#convert-unknown-ndarray-subclasses
```
This is done out of abundance of caution for oddities that can occur when treating `FITS_rec` like an `ndarray`. See below for an example.
There are many places where stdatamodels passes a `FITS_rec`to asdf in a way that is unaware of these oddities (see this run log for a full list of warnings that will appear when asdf 3.0 is released or if testing stdatamodels against …
> Safely convert fitsrec in tree before serializing with asdf

- .github/workflows/ci.yml
- requirements-dev.txt
- tox.ini
This PR enables devdeps testing in github actions allowing us to run tests against numpy 2.0 and other development versions of some key dependencies.
`requirements-dev.txt` is added, listing several key dependencies (asdf, astropy, asdf-astropy numpy) and configuring pip to install development versions (either from git or from available built development versions). scipy is not a direct dependency of stdatmodels but is installed in `requirements-dev.txt` as it's unlikely the development version of numpy will work with the released scipy.
`tox.ini` required minor updates to use the new `requirements-dev.txt` (an existing `devdeps` environment was already configured).
`ci.yml` was updated to run the `devdeps` tox environment which appears as `test-devdeps-xdist`. See a run triggered by this …
> enable devdeps testing

- .github/workflows/ci.yml
- .github/workflows/ci_cron.yml
- .github/workflows/test_devdeps.yml
Resolves [SCSB-79](https://jira.stsci.edu/browse/SCSB-79)
This PR reorganizes CI tests and moves devdeps tests to a new optional workflow that can be started with the label `run devdeps tests`
**Checklist**
> reorganize tests, make devdeps testing optional, unpin latest Python testing, and prepare for possibility of data caching

- CHANGES.rst
- src/stdatamodels/jwst/transforms/models.py
As shown in jwst tests fixing numpy 2.0 deprecations there are a few deprecations from numpy 1.25 that are not yet addressed:
https://github.com/spacetelescope/jwst/actions/runs/6198454984/job/16828931603#step:10:459
A few of these are from code in stdatamodels file `RefractionIndexFromPrism`. ~These warnings are not seen in the stdatamodels CI as not all jwst tests are currently run.~ These warnings can also be seen in our `test_downstream` runs:
https://github.com/spacetelescope/stdatamodels/actions/runs/6175840080/job/16763536280#step:10:1995
This PR updates `RefractionIndexFromPrism` to convert single element ndarrays to scalars before computing sin cos to avoid deprecation warning:
DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in …
> fix numpy scalar handling in RefractionIndexFromPrism

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/gain.schema.yaml
Miri gain files on CRDS now contain the `BAND` keyword.
This PR adds a reference to `keyword_band.schema` to `gain.schema`.
It is not clear to me if at this point the miri gain files should be handled by a more specific schema for the following reasons:
- https://jira.stsci.edu/browse/CRDS-730 mentions a range of possible values, these are a subset but not a match of those defined in`keyword_band.schema` (one example `keyword_band.schema` lists `MEDIUM` which is not listed in the ticket)
- my cursory understanding is that `gain.schema`, used for `GainModel`, is used for all `gain` reference files on crds. There are `gain` files for: `fgs`, `miri`, `nircam`, `niriss` and `nirspec`. Not all of these use the `BAND` keyword and not all of these use the `FILTER` keyword. Although apparently …
> add band to GainModel schema

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/mirmrs_apcorr.schema.yaml
MIRI MRS AP corr files on CRDS now contain a `META.INSTRUMENT.CHANNEL` parameter. 
https://jwst-crds.stsci.edu/browse/jwst_miri_apcorr_0007.asdf
This PR adds the corresponding keyword to the MIRI MRS AP corr schema to keep things in sync and fix the failing test that compares the crds parameters to the schema.
**Checklist**
> add channel to miri apcorr schema

- .github/workflows/ci.yml
- .github/workflows/test_devdeps.yml
`3.x` is now using python 3.12 (instead of python 3.11). This PR updates the CI to use python 3.11 for coverage and jwst jobs
As this PR changes require CI jobs the branch protection rules will need to be updated.
As this PR only changes CI configuration regression tests were not run.
**Checklist**
> update CI for python 3.12

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/amioi.py
- src/stdatamodels/jwst/datamodels/tests/test_models.py
As reported by @rcooper295 using `AmiOIModel.update` results in a `ValidationError`. This is due to the mapping of JWST to OIFITS keywords only during `AmiOIModel.on_save` (which is not called during `update`).
This PR updates `AmiOIModel` to map JWST to OIFITS keywords before calling `validate` (which is called during `update` and also fixes an issue that without this PR `AmiOIModel.validate` would also similarly fail).
Unit tests were added to verify that `AmiOIModel.update` and `AmiOIModel.validate` run successfully for an OIFITS compliant model.
Regression tests run with no errors: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1047/
**Checklist**
> map JWST to OIFITS keywords prior to validate

- src/stdatamodels/fits_support.py
pkg_resources is deprecated. It's use in stdatamodels is limited to parsing the asdf version to check if it's at least 2.6. The pyproject.toml dependencies set a lower pin on asdf version 2.15.0 making the check in the code unnecessary:
https://github.com/spacetelescope/stdatamodels/blob/27c397415ad2d96a1149f492b7906c49862fc7c2/pyproject.toml#L15
This PR removes the use of pkg_resources.
This is causing issues for 3.12 testing as seen in: https://github.com/spacetelescope/stdatamodels/pull/216
Regression tests passed with no errors: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/967/
**Checklist**
> remove use of pkg_resources

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/photom.py
- src/stdatamodels/jwst/datamodels/schemas/mirimg_photom.schema.yaml
Related to [JP-3455](https://jira.stsci.edu/browse/JP-3455)
This PR is related to proposed changes to the PHOTOM step for the MIRI Imager (and coronographs). We add a time-dependent correction to the PHOTOM value. A new datamodel is needed for the PHOTOM reference file.
**Checklist**
> JP-3455: Changes to the MIRI imager PHOTOM datamodel

- CHANGES.rst
- src/stdatamodels/util.py
- tests/test_util.py
updates use of `utcnow` (deprecated in python 3.12) with an equivalent call that returns a non-timezone aware utc timestamp
Regression tests: https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1023/
Showed the expected niriss failures due to crds file updates and also showed 2 failures:
- test_nirspec_missing_msa_fail
- test_nirspec_missing_msa_nofail
As these tests appear to sometimes fail (possibly due to test ordering or io buffering) they were re-run in another test run:
https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/1026/pipeline/199
where they both passed.
This PR removes one of the python 3.12 failures:
```
FAILED tests/test_util.py::test_create_history_entry - …
```
> replace utcnow

- CHANGES.rst
- src/stdatamodels/util.py
- tests/test_util.py
`stdatamodels.util.rebuild_fits_rec_dtype` appears to incorrectly handle unsigned integer columns with shapes. This PR updates `rebuild_fits_rec_dtype` and adds tests for this error.
Closes https://github.com/spacetelescope/stdatamodels/issues/206
Regression tests run with no errors: https://plwishmaster.stsci.edu:8081/blue/organizations/jenkins/RT%2FJWST-Developers-Pull-Requests/detail/JWST-Developers-Pull-Requests/963/pipeline
**Checklist**
> fix rebuild_fits_rec_dtype for shaped columns

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
Resolves [JP-3235](https://jira.stsci.edu/browse/JP-3235)
This PR adds a new step status keyword to the JWST datamodels for the new "nsclean" step being added in B10.1.
**Checklist**
> JP-3235: Add step status keyword for NSClean

- CHANGES.rst
- src/stdatamodels/fits_support.py
- src/stdatamodels/jwst/datamodels/util.py
- src/stdatamodels/model_base.py
- tests/test_fits.py
Deprecate `cast_arrays` argument to `from_fits_hdu` and `cast_fits_arrays` argument to `Datamodel.__init__`.
These appear to be unused (outside of the `test_ndarray_validation` test). Deprecating (and eventually removing them) is work towards removing uses of `FITS_rec`.
Regression tests show 2 seemingly unrelated errors and no `DeprecationWarning` with the message introduced in this PR (so no code in the regression tests uses `cast_arrays` or `cast_fits_arrays`): https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/964/
The errors are:
```
[stable-deps] test_nirspec_missing_msa_fail – jwst.regtest.test_nirspec_exceptions3s
[stable-deps] test_nirspec_missing_msa_nofail – jwst.regtest.test_nirspec_exceptions
```
Both with similar failed asserts
```
AssertionError: …
```
> deprecate cast_fits_array and cast_arrays

- CHANGES.rst
- docs/source/conf.py
Applies the same fix as in: https://github.com/spacetelescope/jwst/pull/7524
Fix search in docs by including jquery in the docs conf file.
**Checklist**
> Fix search in docs by adding jquery to docs conf

- CHANGES.rst
- src/stdatamodels/model_base.py
This PR allows control of memory mapping when opening an asdf file using `DataModel(asdf_filename)`. Control of memory mapping already exists for FITS files (through the `memmap` argument which is reused here).
asdf is making a few changes to memory mapping. This PR will help to prepare stdatamodels for those changes. Specifically, asdf will no longer force closure of memory mapped view of arrays (which can and often results in a segfault when an array access fails during an attempt to access the closed file). Instead, asdf will release all references to the opened memory map and rely on the garbage collector to close the file (see this asdf PR for more details: https://github.com/asdf-format/asdf/pull/1668). This works in most situations but is complicated in a few stdatamodels tests …
> allow control of memmapping for asdf files

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/tests/test_fits.py
- src/stdatamodels/properties.py
Resolves [JP-3482](https://jira.stsci.edu/browse/JP-3482)
Closes [spacetelescope/jwst#8109]
When a `DataModel` containing a table extension is loaded from a FITS file, stdatamodels currently discards the units defined in the `TUNITS` headers. This is due to a `_cast` from a FITS_rec to a ndarray (to protect against the numerous gotchas in FITS_rec):
https://github.com/spacetelescope/stdatamodels/blob/b7eada9ee768691bafbb9eb6b38b18c3eb50d85b/src/stdatamodels/properties.py#L86
then a conversion back to a FITS_rec to allow jwst code to continue to interact with a FITS_rec:
https://github.com/spacetelescope/stdatamodels/blob/b7eada9ee768691bafbb9eb6b38b18c3eb50d85b/src/stdatamodels/properties.py#L89
This PR is an alternative to #238 and a stop-gap measure until #240 can be resolved. …
> restore column units on cast

- CHANGES.rst
- src/stdatamodels/fits_support.py
- src/stdatamodels/jwst/datamodels/schema_editor.py
This PR removes uses of the optional `json_id` argument for callbacks passed to `asdf.treeutil.walk_and_modify`.
In `fits_support` this argument was unused and removal has no effect.
In `schema_editor` it is likely better to not use this argument (it's use might lead to bugs like in https://github.com/asdf-format/asdf/pull/1716).
For some extra context, `json_id` contains the string value under the key "id" of the most closely nested dictionary for the contained object processed in the callback. This is useful for draft 4 jsonschema so any reference fragments can be resolved using the uri stored in the "id" (see [this schema for an example id](https://github.com/spacetelescope/stdatamodels/blob/44a5691d56e001f5f1a9c54167481fb73be14813/src/stdatamodels/jwst/datamodels/schemas/abvegaoffset.s …
> drop use of json_id in walk_and_modify callbacks

- tests/test_fits.py
pytest 8 includes a change to how "pytest.warns" behaves (it now re-emits non-matched warnings). Running the stdatamodels test suite against pytest 8 (rc1) there is one failing test `test_ndarray_validation` due to this change.
This PR updates the warning filters in `test_ndarray_validation` to work with pytest 8.
**Checklist**
> update warning filters in tests for pytest 8

- .github/workflows/ci.yml
- .github/workflows/test_devdeps.yml
- CONTRIBUTING.md
- README.md
This PR updates the CI and docs to refer to a renamed "main" branch.
As no downstream package appears to reference a specific branch for stdatamodels (and instead uses the default branch) we should be able to:
- rename the default branch to "main"
- merge this PR
It's possible codecov may need to be updated to use "main" (if it's not using the default branch).
Github does quite a number of helpful things when the branch is renamed (see https://github.com/github/renaming#renaming-existing-branches) so if acceptable I would propose we rename the branch, merge this PR, and deal with any fallout (although I do not expect any).
**Checklist**
> prepare for rename to main

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/mask.schema.yaml
- src/stdatamodels/jwst/datamodels/tests/test_schema_against_crds.py
Addresses [JP-3520](https://jira.stsci.edu/browse/JP-3520)
crds added 'ngroups' as a parkey for mask reference files. This is causing test failures (that check the schema and parkeys).
See the test failure here: https://github.com/asdf-format/asdf/actions/runs/7629799922/job/20784057576?pr=1739#step:10:718
This PR adds 'ngroups' to the mask schema to bring these two projects into alignment.
**Checklist**
> JP-3520: Add ngroups to mask schema

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
Resolves [JP-3449](https://jira.stsci.edu/browse/JP-3449)
Closes [spacetelescope/jwst#8036]
This PR addresses adding TMEASURE to the JWST core schema.
**Checklist**
> JP-3449: Add TMEASURE keyword to core schema

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
Resolves [JP-3528](https://jira.stsci.edu/browse/JP-3528)
Closes spacetelescope/jwst#8252
This PR adds "IMAGER" as another allowed value for the "MRSPRCHN" keyword, in order to support proper handling of MIRI MRS and Imager exposures done in parallel.
**Checklist**
> JP-3528: Add "IMAGER" as allowed value for MRSPRCHN keyword

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/barshadow.schema.yaml
CRDS now uses `GRATING` for `barshadow` reference files.
This PR updates the `barshadow` schema to include the `grating` keyword schema.
See: https://jwst-crds.stsci.edu/browse/jwst_nirspec_barshadow_0007.rmap
**Checklist**
> add grating keyword to barshadow schema

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/mask.schema.yaml
Resolves [JP-3520](https://jira.stsci.edu/browse/JP-3520)
https://github.com/spacetelescope/stdatamodels/pull/249 followed the normal pattern of adding new keywords/attributes to reference file schemas. This involves adding a `$ref` to the existing `keyword_<...>` schema for the new keyword used as a selector in crds.
However, in this case (perhaps the first of its kind in JWST) the selector type does not match the keyword type where the selector is a string `BETWEEN 0 50` and the keyword `NGROUPS` expects an `integer`. See:
https://jwst-crds.stsci.edu/browse/jwst_miri_mask_0055.fits
and:
https://github.com/spacetelescope/stdatamodels/blob/b7c7bcd83b7a32d908e3f63c5dece313b3611f7a/src/stdatamodels/jwst/datamodels/schemas/keyword_ngroups.schema.yaml#L13-L16
This PR fixes the issue by …
> allow non-integer ngroups for mask ref file

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/__init__.py
- src/stdatamodels/jwst/datamodels/nrm.py
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/nrm.schema.yaml
- src/stdatamodels/jwst/datamodels/tests/test_schema_against_crds.py
This PR adds support (a schema and model) for the new NIRISS `nrm`  reference file:
https://jwst-crds-test.stsci.edu/browse/jwst_niriss_nrm_0002.fits
Local tests were performed to confirm that this file loads and the `nrm` array is available at the `nrm` attribute:
```python
>> import stdatamodels.jwst.datamodels as dm
>> m = dm.open('jwst_niriss_nrm_0002.fits')
>> assert isinstance(m, dm.NRMModel)
>> m.nrm
array([[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.],
...,
[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.]], dtype='>f4')
```
The local testing is important as this file only exists on https://jwst-crds-test.stsci.edu/ and the CI uses the non-test public crds: https://jwst-crds.stsci.edu/ …
> add schema and model for nrm reference file

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/multispec.schema.yaml
Partially resolves [JP-3169](https://jira.stsci.edu/browse/JP-3169)
<!Resolves [RCAL-nnnn](https://jira.stsci.edu/browse/RCAL-nnnn) -->
Is needed to close spacetelescope/jwst#7773
This PR updates the MultiSpec model to include the xstart, xstop, ystart, ystop values (if they are defined) so they can be recorded in the FITS header
The extraction x center and y center were already defined with keyword values of EXTR_X, EXTR_Y.
Since the extraction locations are related to these values I picked
EXTRXSTR: x start of extraction region
EXTRXSTP: x stop of extraction region
EXTRYSTR: y start of extraction region
EXTRYSTP: y stop of extraction region
But these value can be changed if a better set can be found
**Checklist**
> Update MultiSpec schema to provide keywords for recording extraction characteristics

- src/stdatamodels/jwst/datamodels/tests/test_schema_against_crds.py
The `test_schema_against_crds` tests are failing on main:
https://github.com/spacetelescope/stdatamodels/actions/runs/8096660095/job/22125905730
due to a lack of mapping between the now-available `emicorr` reference file and the `EmiModel` model used for this file type.
This PR updates the test for the mapping in the test to map `emicorr` to `EmiModel`.
**Checklist**
> update test mapping emicorr reference files to EmiModel

- src/stdatamodels/jwst/datamodels/drizproduct.py
- src/stdatamodels/jwst/datamodels/multiprod.py
- tox.ini
This PR removes some warnings filters including:
- filter resets for jwst tests in the CI for this package
- non-context calls to `warnings.simplefilter('default')` during creation of deprecated models `DrizProductModel` and `MultiProductModel`
The second item above may help jwst cleanup of warning filters as the non-context use of `simplefilter('default')` will reset any prior calls to `simplefilter('error')` (or similar).
**Checklist**
> remove global changes to warning filters

- CHANGES.rst
- src/stdatamodels/validate.py
During validation on assignment `check_value` a call is made to `asdf.schema.validate`. This PR speeds up that call by passing in a `ctx` `AsdfFile` instance (one used a few lines prior).
This should speed up all validated `DataModel` assignments including those performed during `open` (discussed: https://github.com/spacetelescope/stdatamodels/pull/270). For example opening:
https://bytesalad.stsci.edu/ui/repos/tree/General/jwst-pipeline/dev/nircam/image/jw01538046001_03105_00001_nrcblong_rate.fits?clearFilter=true
with `skip_fits_update=False` (which will result in assignment to all parts of the model linked to the fits data) without this PR takes 177 ms. With this PR opening the same model takes 72 ms.
**Checklist**
> provide existing asdf file to validate

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
Partially resolves [JP-3465](https://jira.stsci.edu/browse/JP-3465)
This PR addresses removal of the TEXPTIME (product exposure time) keyword, since it is functionally redundant with XPOSURE and EFFEXPTM and is not used by any high-level data processing scripts we know about.
**Checklist**
> JP-3465: removed product exposure time TEXPTIME

- CHANGES.rst
- docs/source/jwst/datamodels/models.rst
- src/stdatamodels/jwst/datamodels/tests/test_open.py
- src/stdatamodels/jwst/datamodels/tests/test_util.py
- src/stdatamodels/jwst/datamodels/util.py
See the below issue for the motivation behind this PR.
In brief, this PR deprecates `check_memory_allocation` which has 1 use in jwst:
https://github.com/spacetelescope/jwst/blob/e1215951096c2057df6abff6087b7f12d429ab25/jwst/resample/resample.py#L144-L146
Effectively this function:
- allocates a large array
- checks it's memory consumption against "allowed" amount
- then throws out the array
If the check passes, the array is re-allocated (and hopefully the original is garbage collected). If the check fails it is certain that the amount of "allowed" memory usage was already exceeded (to perform the check).
Work towards addressing: https://github.com/spacetelescope/stdatamodels/issues/272
https://github.com/spacetelescope/jwst/pull/8324 removes the 1 use in jwst. Keeping this PR draft until …
> deprecate check_memory_allocation

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/oifits.schema.yaml
The oifits standard:
https://www.aanda.org/articles/aa/pdf/2017/01/aa26405-15.pdf
limits the `SPECTYP` and `TARGET` columns of `OI_TARGET` to 16 characters. The schema currently defines them as 32. This does not raise validation errors with `oifits-check` (part of [oifitslib](https://github.com/jsy1001/oifitslib)) but does raise validation errors for the online validator: http://oival.jmmc.fr/validate.xql
This PR reduces the number of characters to 16.
**Checklist**
> limit oifits SPECTYP and TARGET to 16 characters

- CHANGES.rst
During conflict resolution a changelog error was introduced in:
https://github.com/spacetelescope/stdatamodels/pull/281
This PR fixes the changelog by removing the extra `<<<<<<< HEAD`.
**Checklist**
> fix error in changelog

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/group.schema.yaml
Resolves [JP-3558](https://jira.stsci.edu/browse/JP-3558)
Closes [#8323](https://github.com/spacetelescope/jwst/issues/8323)
This PR prevents values from wrapping around the limit of the int16 range in observations with a large number of integrations.
**Checklist**
> JP-3558: update integration_number dtype in group schema

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
Resolves [JP-3580](https://jira.stsci.edu/browse/JP-3580)
Closes spacetelescope/jwst#8367
This PR addresses adding ALL_MRS to the enum list for keyword MRSPRCHN.
**Checklist**
> JP-3580 Update MRSPRCHN allowed values in keyword schema

- CHANGES.rst
- pyproject.toml
- src/stdatamodels/fits_support.py
- src/stdatamodels/jwst/datamodels/schemas/abvegaoffset.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/ifuslicer.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/keyword_lampstate.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/msa.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/nrsfs_apcorr.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/regions.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/wavecorr.schema.yaml
- src/stdatamodels/jwst/datamodels/tests/test_integration.py
- src/stdatamodels/jwst/transforms/extensions.py
- src/stdatamodels/jwst/transforms/resources/manifests/jwst_transforms-1.1.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/coords-1.1.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/grating_equation-1.1.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/gwa_to_slit-1.1.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/logical-1.1.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/miri_ab2slice-1.1.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/nircam_grism_dispersion-1.1.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/niriss_grism_dispersion-1.1.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/niriss_soss-1.1.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/refraction_index_from_prism-1.1.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/rotation_sequence-1.1.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/slit_to_msa-1.0.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/slit_to_msa-1.1.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/snell-1.1.0.yaml
- tests/test_embedded_asdf.py
This PR adds a test for "resources" (schemas, manifests, metaschemas) registered with asdf. The test checks:
- that every resource in the various resource directories is registered with asdf
- that the "id" in the resource matches the "uri" used to register the resource
There are a few issues with the resources that this test revealed:
```
===================================================================================================== short test summary info ======================================================================================================
FAILED test_integration.py::test_resource_id[resource19] - AssertionError: id[http://stsci.edu/schemas/jwst_datamodel/nrsmos_apcorr.schema] for resource[/Users/bgraham/projects/src/stdatamodels/src/stdatamodels/jwst/datamodels/sc …
```
> Add asdf resources test and update schemas for new transform schemas

- CHANGES.rst
- src/stdatamodels/fits_support.py
Opening a jwst file with many (~550) extensions (level 2 output for nirspec mos mode) take ~9 seconds (when `skip_fits_update=True`). Opening the same file with `skip_fits_update=False` takes longer, ~26 seconds. Surprisingly, a large portion of the added time is spent in calls to `get_hdu`.
Using `cProfile` and `skip_fits_update=False` opening now takes ~60 seconds (due to profiling overhead) and the rendered profile (with snakeviz) is as follows:
zooming into `_load_from_schema` reveals ~40 seconds in `get_hdu`
This PR adds a `hdu_cache` to skip repeated indexing the hdulist (which in some conditions for this file takes 2-3 ms). With this PR opening the same file with `skip_fits_update=False` (and no profiling) takes 12 seconds and with `skip_fits_update=True` still takes 9 seconds …
> add cache for slow hdu indexing

- CHANGES.rst
- src/stdatamodels/fits_support.py
- tests/test_fits.py
Convert ``FITS_rec`` instances read from old files where a hdu was linked in the old schema (but is no longer linked) when rewriting files.
Resolves [JP-3555](https://jira.stsci.edu/browse/JP-3555)
Regression tests run:
https://plwishmaster.stsci.edu:8081/job/RT/job/JWST-Developers-Pull-Requests/1250/
As this is aimed to fix warnings like:
```
/data1/jenkins/workspace/RT/JWST-devdeps/miniconda/envs/tmp_env0/lib/python3.11/site-packages/asdf/yamlutil.py:282: AsdfConversionWarning: A ndarray subclass (<class 'astropy.io.fits.fitsrec.FITS_rec'>) was converted as a ndarray. This behavior will be removed from a future version of ASDF. See https://asdf.readthedocs.io/en/latest/asdf/config.html#convert-unknown-ndarray-subclasses
```
which by-default do not produce errors. The log output of the …
> safely convert FITS_rec for non-schema data

- CHANGES.rst
- docs/source/jwst/datamodels/models.rst
- src/stdatamodels/fits_support.py
- src/stdatamodels/jwst/datamodels/tests/test_models.py
- src/stdatamodels/jwst/datamodels/util.py
- src/stdatamodels/model_base.py
- tests/test_fits.py
`skip_fits_update` is [unused in jwst](https://github.com/search?q=repo%3Aspacetelescope%2Fjwst+skip_fits_update&type=code)
as is [SKIP_FITS_UPDATE](https://github.com/search?q=repo%3Aspacetelescope%2Fjwst+SKIP_FITS_UPDATE&type=code).
This PR deprecates their usage. Their eventual removal will allow `stdatamodels` to reduce data duplicated between the fits headers/hdus and the `ASDF` extension (including `extra_fits` which is entirely duplicated in both).
This is a step towards the eventual removal of `skip_fits_update`, see: https://github.com/spacetelescope/stdatamodels/issues/271
**Checklist**
> deprecate skip_fits_update

- CHANGES.rst
- pyproject.toml
- src/stdatamodels/jwst/transforms/converters/tests/test_models.py
- tests/test_embedded_asdf.py
Increases minimum asdf version to 3.1.0 (inline with jwst: https://github.com/spacetelescope/jwst/blob/master/pyproject.toml#L22) and switches `_force_raw_types` usage to `load_tree`.
Also updates one test that fails with ASDF standard 1.6.0 as the default due to an incorrect assumption about the tag version:
https://github.com/spacetelescope/stdatamodels/blob/50751a8f91a4cd8a685dfb7bc692a4fe30c08f18/src/stdatamodels/jwst/transforms/converters/tests/test_models.py#L76-L77
assumes the tag will be `1.0.0`. With ASDF standard 1.6.0 the tag will be `1.1.0`:
https://github.com/spacetelescope/stdatamodels/blob/50751a8f91a4cd8a685dfb7bc692a4fe30c08f18/src/stdatamodels/jwst/transforms/resources/manifests/jwst_transforms-1.1.0.yaml#L46-L47
**Checklist**
> increase asdf version, switch _force_raw_types for load_yaml

- CHANGES.rst
- src/stdatamodels/validate.py
- tests/test_validation.py
While looking into `resample` memory usage I found a way that repeated assignments to a datamodel attribute can result in accumulation of memory (until the model is written). An example is as follows:
```python
import jwst.datamodels as dm
import numpy as np
m = dm.ImageModel()
sci = m.data
m.data = np.zeros_like(sci)  # assign a "zeros" array to data
m.data = np.ones_like(sci)   # overwrite the "zeros" with a new "ones" array
```
Running the example the "zeros" array should be garbage collectable by python after the data is overwritten with the "ones" array. However this is not the case on the current main branch with the latest asdf and instead both the "zeros" and "ones" arrays will persist in memory until the model is written to disk (or freed). This is due to the assignment …
> Free references to overwritten attributes

- src/stdatamodels/properties.py
Fixes: #42
These methods are [no longer supported as of python 3](https://docs.python.org/3.9/whatsnew/3.0.html?highlight=__getslice__#operators-and-special-methods).
**Checklist**
> remove python 2 slicing api

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
Resolves [JP-3581](https://jira.stsci.edu/browse/JP-3581)
Closes #8369
This PR adds a new header keyword to the cal_step in the core schema to reflect the addition of the new badpix_selfcal step in JWST.
**Checklist**
> JP-3581: add badpix_selfcal step to core schema

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/util.py
- src/stdatamodels/model_base.py
follow-on to https://github.com/asdf-format/asdf/pull/1797
**Checklist**
> replace usages of ``copy_arrays`` with ``memmap``

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/dark.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/superbias.schema.yaml
- tox.ini
A new crds context added grating as selection criteria requiring updates to the dark and superbias reference model schemas.
This PR also removes installing dev stpipe for the jwst test. That dependency should be left up to jwst.
**Checklist**
> add grating keyword to dark and superbias reference model schemas

- CHANGES.rst
- src/stdatamodels/fits_support.py
- src/stdatamodels/model_base.py
- tests/test_models.py
`ignore_version_mismatch` no longer does anything (see https://github.com/asdf-format/asdf/issues/1812) since it was only used by the legacy asdf extension API removed in asdf 3.0.0.
This PR removes all uses of the setting.
There are no uses of `ignore_version_mismatch` in jwst: https://github.com/search?q=repo%3Aspacetelescope%2Fjwst%20ignore_version_mismatch&type=code
**Checklist**
> remove unused ignore_version_mismatch

- changes/319.feature.rst
- src/stdatamodels/jwst/datamodels/schemas/irs2.schema.yaml
Partially addresses [JP-3664](https://jira.stsci.edu/browse/JP-3664)
Closes [jwst/#8578](https://github.com/spacetelescope/jwst/issues/8578)
Partially addresses [jwst/#8580](https://github.com/spacetelescope/jwst/issues/8580)
This PR addresses a bug exposed by testing numpy 2.0 - the irs2 datamodel specifies arrays to be of type uint8, but operations in refpix promoted them to uint16 implicitly in numpy<2.0. Numpy 2.0 does not implicitly type promote in this case, leading to an integer overflow. This PR updates the specified array datatype to uint16.
**Checklist**
> JP-3664: Numpy 2.0 exposed implicit type promotion

- changes/327.bugfix.rst
- pyproject.toml
- src/stdatamodels/jwst/_tests/test_schemas.py
- src/stdatamodels/jwst/datamodels/schemas/abvegaoffset.schema.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/coords-0.7.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/coords-1.0.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/coords-1.1.0.yaml
Adds a test that checks that schemas (both datamodels and transforms) contain keywords that are "understood" by stdatamodels. This compares keywords against:
- known validation keywords (by polling the validator)
- extra known keywords (like title, description, fits_hdu, blend_table, etc)
The test is failing due to schema issues:
```
FAILED test_schemas.py::test_schema_contains_only_known_keywords[http:/stsci.edu/schemas/jwst_datamodel/abvegaoffset.schema] - AssertionError: {'detector', 'pupil', 'filter'} found at ['abvega_offset', 'anyOf'] in http://stsci.edu/schemas/jwst_datamodel/abvegaoffset.schema
FAILED test_schemas.py::test_schema_contains_only_known_keywords[http:/stsci.edu/schemas/jwst_pipeline/coords-1.0.0] - AssertionError: {'object'} found at [] in …
```
> add check that all schemas have understood keywords

- changes/328.feature.rst
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
Addresses [JP-3639](https://jira.stsci.edu/browse/JP-3639)
This PR adds the cal_step keyword for the newly added step `clean_flicker_noise`.  
</details>
> Add cal_step status keyword for clean_flicker_noise

- changes/329.feature.rst
- src/stdatamodels/jwst/datamodels/level1b.py
- src/stdatamodels/jwst/datamodels/tests/test_models.py
Resolves [JP-2349](https://jira.stsci.edu/browse/JP-2349)
This PR addresses validation issues encountered when opening `jwst` uncal files generated with DMS Ops builds <11.1 and using `stdatamodels`>=2.1.0. This most recent release of `stdatamodels` changed the number of columns in the `moving_target_table` schema, which leads to validation errors when opening any existing file with an old moving target extension. For any users attempting to load an outdated uncal file, this PR will check for the missing columns and add nan-filled columns if they are missing.
- ``changes/<PR#>.removal.rst``: …
> JP-2349: Add workaround to load old files with new moving_target_table schema

- .github/workflows/ci.yml
Similar to:
https://github.com/spacetelescope/crds/pull/1086
fixes the curl command to add the second required parameter.
</details>
> fix curl getting of context

- changes/348.bugfix.rst
- src/stdatamodels/jwst/datamodels/irs2.py
- src/stdatamodels/jwst/datamodels/tests/test_models.py
Closes #347
This changes the parent class for IRS2Model to ReferenceFileModel.
Testing locally I was able to (with this PR) open https://jwst-crds.stsci.edu/browse/jwst_nirspec_refpix_0017.fits and run "validate" without issue. Let me know if more tests (not covered by the CI and regtests) would be helpful.
Will need regression tests run (when they're working again). Opening for review in the meantime.
Regression tests all passed: https://github.com/spacetelescope/RegressionTests/actions/runs/11484201187/job/31961401428
- …
> make IRS2Model inherit from ReferenceFileModel

- changes/352.removal.rst
- src/stdatamodels/jwst/datamodels/conftest.py
- src/stdatamodels/jwst/datamodels/schema_editor.py
This PR adds a UserWarning if the schema_editor submodule is imported.
https://github.com/spacetelescope/jwst/pull/8909 removed its use in jwst
before merging this PR I'll make an issue to track the removal of schema_editor. I'm not sure if this qualifies as "public API" (since it's undocumented and untested in this package) so I'm ok removing it in the next minor version (so it's not picked up by current jwst releases).
Regression tests running at: https://github.com/spacetelescope/RegressionTests/actions/runs/11632063641 …
> deprecate schema_editor

- README.md
- changes/338.doc.rst
- docs/source/jwst/datamodels/attributes.rst
- docs/source/jwst/datamodels/index.rst
- docs/source/jwst/datamodels/schemas.rst
- src/stdatamodels/jwst/datamodels/tests/test_integration.py
This is far from a complete cleanup but addresses a few docs issues:
- Remove a redundant list of datamodels in the docs. https://stdatamodels.readthedocs.io/en/latest/jwst/datamodels/index.html#module-jwst.datamodels contains a list that is automatically updated and links to the models. This PR removes the static list (which otherwise requires manual updates): https://stdatamodels.readthedocs.io/en/latest/jwst/datamodels/attributes.html#list-of-current-models
- Updates README to make it clear this package is for JWST (not generally for STScI missions)
- Adds a brief description of the schema types in this package (data model, reference file, transform)
I also included a test that checks data model schemas to verify they either reference:
- referencefile.schema (for reference file …
> Add schema types description to docs (and misc cleanup)

- changes/361.feature.rst
- src/stdatamodels/jwst/datamodels/schemas/nrm.schema.yaml
Closes #359
The NRM reference files contain FITS keywords useful to CAL.
https://jwst-crds.stsci.edu/browse/jwst_niriss_nrm_0001.fits
This PR adds those keywords to the schema so they are accessible via the datamodel interface:
- `model.flat_to_flat`
- `model.x_a1` etc...
Regression tests running at https://github.com/spacetelescope/RegressionTests/actions/runs/11802888443
</details>
> add fits keywords to NRMModel schema

- changes/364.bugfix.rst
- src/stdatamodels/jwst/datamodels/tests/test_models.py
- src/stdatamodels/schema.py
- tests/test_schema.py
This PR updates `merge_property_trees` to retain the schema `id` (and other "top level" items/attributes). This fixes the issue where `model.schema["id"]` does not match the "id" of the schema (see #308).
This PR also drops the use of OrderedDict fixing #40.
Finally the CI goblins revealed that shuffling order of tests can cause `test_defined_models_up_to_date` to fail:
https://github.com/spacetelescope/stdatamodels/actions/runs/11901768169/job/33165405951
if executed after `test_model_with_nonstandard_primary_array` which defines a test model class that isn't prefixed with `_`. This PR adds a `_` prefix to the test class to avoid this intermittent issue.
Fixes: https://jira.stsci.edu/browse/JP-2137
Closes #308
Closes #40
Regression tests: …
> Retain `id` and other top-level attributes in `merge_property_trees`

- changes/367.feature.rst
- src/stdatamodels/validate.py
This PR adds an "always" filter for `ValidationWarning`s at the end of the warning filter list.
This addresses an issue where for an interactive python session (using the standard python REPL) only the first call to "validate" for a particular validation error will result in a warning:
```python
> from stdatamodels.jwst import datamodels as dm
> m = dm.ImageModel()
> m.meta.instrument._instance['detector'] = "foo"
> m.validate()
ValidationWarning: While validating...
> m.validate()
```
This is a byproduct of the "default" python warning filter which for a particular warning based on message, category and line number will only show the warning the first time. This PR adds an "always" for `ValidationWarning` to override this behavior but adds it to the end of the filter list so that a user …
> add filter for ValidationWarning

- changes/357.feature.rst
- src/stdatamodels/jwst/datamodels/schemas/ami.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/amioi.schema.yaml
- src/stdatamodels/jwst/datamodels/tests/test_models.py
- src/stdatamodels/jwst/datamodels/tests/test_schema.py
Required for https://github.com/spacetelescope/jwst/pull/8846
This PR adds the `CALIB` keyword and wcsinfo subschema to the `AmiOIModel` schema.
Regression tests running at https://github.com/spacetelescope/RegressionTests/actions/runs/11978383053
</details>
> Add `CALIB` and wcsinfo to ami schema

- changes/375.doc.rst
- docs/source/jwst/datamodels/schemas.rst
Link to updated docs:
https://stdatamodels--375.org.readthedocs.build/en/375/jwst/datamodels/schemas.html#reference-file-keywords
Expand documentation for reference file schemas to mention `keyword_*` references and "pattern" `keyword_p*` references.
</details>
> expand reference file schema docs

- changes/377.feature.rst
- src/stdatamodels/jwst/datamodels/__init__.py
- src/stdatamodels/jwst/datamodels/multispec.py
- src/stdatamodels/jwst/datamodels/schemas/mrs_multispec.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/mrs_spec.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/mrs_spectable.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/specmeta.schema.yaml
- src/stdatamodels/jwst/datamodels/spec.py
Partially resolves [JP-3790](https://jira.stsci.edu/browse/JP-3790)
Adds spectral models to support a few extra columns for MIRI MRS spectral data: residual fringe corrected flux, surface brightness, and background.  
In order to be as minimally disruptive as possible to existing spectral data models and to MIRI MRS users, I implemented this as a new parallel set of datamodels, with the extra columns defined in the mrs_spectable schema (paralleling the spectable schema), to be stored in an EXTRACT1D HDU.   The mrs_spectable schema is included in MRSSpecModel (paralleling SpecModel) for a single spectrum and in MRSMultiSpecModel (paralleling MultiSpecModel) for lists of spectra, in the spec_table property for each.  In order to avoid duplicating the additional metadata in MultiSpecModel, I …
> JP-3790: MIRI MRS models to hold residual fringe correction 

- .github/workflows/ci.yml
- .github/workflows/ci_cron.yml
- .pre-commit-config.yaml
- .ruff.toml
- changes/392.removal.rst
- docs/rtd_environment.yaml
- docs/source/conf.py
- pyproject.toml
- src/stdatamodels/jwst/transforms/converters/tests/test_models.py
- src/stdatamodels/util.py
- tests/test_util.py
Now that jwst has dropped 3.10 this package can drop 3.10 (per SPEC 0).
This PR:
- drops python 3.10 support
- increases the numpy and astropy minimum versions (by SPEC 0)
- updates the CI and docs removing 3.10 usage
</details>
> Drop python 3.10 support

- changes/395.bugfix.rst
- src/stdatamodels/jwst/datamodels/tests/test_models.py
- src/stdatamodels/properties.py
- tests/test_models.py
Closes #307 
This PR addresses a bug when instantiating datamodels from an array shape.  The problem is discussed in detail on the issue, but in short, the input shape was not checked against the schema `ndim` attribute when creating a default array
</details>
> Validate dimension when instantiating datamodel from shape

- changes/399.misc.rst
- pyproject.toml
This PR updates a few dependencies to match those in jwst:
- asdf-astropy to 0.6.0 (pending https://github.com/spacetelescope/jwst/pull/9177)
- asdf to [3.3](https://github.com/spacetelescope/jwst/blob/d8033b3dd52a15c40fb034eededb4684afdd03f3/pyproject.toml#L21)
- astropy to [6.1](https://github.com/spacetelescope/jwst/blob/d8033b3dd52a15c40fb034eededb4684afdd03f3/pyproject.toml#L22)
</details>
> increase minimum versions to match jwst

- changes/400.removal.rst
- src/stdatamodels/model_base.py
- tests/test_models.py
Closes #16 
This PR removes the previously-deprecated `DataModel.get_fileext()` method. The method is unused by JWST.
</details>
> Remove deprecated get_fileext() method

- changes/401.bugfix.rst
- src/stdatamodels/jwst/datamodels/nirspec_flat.py
- src/stdatamodels/jwst/datamodels/tests/test_nirspec_flat.py
Closes #186 
This PR fixes a bug where attempting to initialize a `NirspecQuadFlatModel` from a `NirspecFlatModel` would raise `TypeError: dynamic_mask() missing 1 required positional argument: 'mnemonic_map'`.
</details>
> Fix bug preventing NirspecQuadFlatModel instantiation from NirspecFlatModel

- changes/403.bugfix.rst
- src/stdatamodels/jwst/datamodels/tests/test_models.py
- src/stdatamodels/model_base.py
- tests/test_models.py
Closes #307 
This PR fixes a bug that allowed initialization of a datamodel from a different datamodel with an incompatible schema.  For example, a CubeModel could be used as input to an ImageModel, e.g., `model = ImageModel(CubeModel(10,10,10))`, leading to a situation where the `ImageModel` contained a 3-D data array that was incompatible with its schema `ndim`.  This PR forces validation of arrays when attempting this kind of assignment.
</details>
> Force array validation when initializing a datamodel from another datamodel of different type

- src/stdatamodels/filetype.py
- tests/test_filetype.py
Partially resolves [JP-3884](https://jira.stsci.edu/browse/JP-3884)
Closes #387 
This PR switches `filetype.check()` from os.path to pathlib.Path.
</details>
> Replace os.path with pathlib in filetype check

- changes/424.removal.rst
- src/stdatamodels/model_base.py
- tests/test_models.py
This PR deprecates the unused `Datamodel.read` and `Datamodel.write`.
`read` is a little odd. It needs to be called using a `Datamodel` instance (not the class) which I suspect is not the intent. However it's unused, untested and being removed so that bug will be "fixed" when it's removed.
Regression tests: https://github.com/spacetelescope/RegressionTests/actions/runs/13553243677
</details>
> Deprecate Datamodel.read Datamodel.write

- changes/393.feature.rst
- src/stdatamodels/jwst/datamodels/__init__.py
- src/stdatamodels/jwst/datamodels/schemas/specwcs_miri_lrs.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/specwcs_nircam_grism.schema.yaml
- src/stdatamodels/jwst/datamodels/tests/test_schema_against_crds.py
- src/stdatamodels/jwst/datamodels/tests/test_specwcs_mirilrs_datamodel.py
- src/stdatamodels/jwst/datamodels/wcs_ref_models.py
Helps Resolve [JP-3848](https://jira.stsci.edu/browse/JP-3848)
This PR replaces #382. There we too many conflicts to resolve easily after the code style changes were made. 
Closes #
Corresponding jwst PR: https://github.com/spacetelescope/jwst/pull/9193
This PR adds a datamodel of the reference file, specwcs, for MIRI LRS data. It can be used for fixed slit or slitless data. The reference file for fixed slit contains the V2,V3 corners of the slit. These values are not in the slitless reference file and default to None when the reference files are read in using the data models
- …
> Add miri lrs spec wcs model

- .github/workflows/ci_cron.yml
- src/stdatamodels/jwst/datamodels/tests/test_models.py
- src/stdatamodels/jwst/datamodels/tests/test_schema.py
- tests/test_embedded_asdf.py
- tests/test_fits.py
- tests/test_history.py
- tox.ini
This PR updates the scheduled run windows tests to not run the crds integration tests. The crds integration tests are failing on windows due to some path/setup issue https://github.com/spacetelescope/stdatamodels/actions/runs/13753985050/job/38458565540 As these tests are designed to compare the schema against the crds reference files it doesn't seem worthwhile to run these on windows.
This PR also updates a few unit tests that fail on windows since windows does not allow overwriting an open file.
- …
> skip crds schema comparison tests on windows and fix a few unit tests for windows

- changes/443.bugfix.rst
- src/stdatamodels/fits_support.py
- src/stdatamodels/jwst/datamodels/tests/test_multislit.py
- src/stdatamodels/validate.py
- tests/test_validation.py
Closes #279
This PR fixes the ndim, max_ndim and datatype validation during FITS array writing by yielding from the corresponding validators (these return generators that are not consumed on main).
This PR also fixes the `if` check for `dtype` to instead check for `datatype` (the keyword used in the schema) and uses the custom `_validate_datatype` defined in this package (rather than `validate_dtype` from asdf which doesn't support `ndim` in structured datatypes or `allow_extra_columns`.
An update to one of the `test_multislit.py` unit tests was required where a float64 was being assigned to an array with a float32 dtype defined in the schema.
jwst regression tests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/13841630347/job/38773673047
<details><summary>news …
> fix validators run during fits array writing

- changes/450.removal.rst
- src/stdatamodels/model_base.py
- tests/test_models.py
This PR deprecates `Datamodel.open_asdf` which is unused outside of this package.
See https://github.com/spacetelescope/stdatamodels/issues/299
Regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/13864903866
failures match those on main: https://github.com/spacetelescope/RegressionTests/actions/runs/13864937894/job/38801959229
</details>
> deprecate open_asdf

- docs/source/jwst/datamodels/models.rst
- tests/conftest.py
I noticed that I left out:
- removing `SKIP_FITS_UPDATE` from the docs
- removing `SKIP_FITS_UPDATE` from conftest
from #380
This PR makes those changes.
</details>
> remove SKIP_FITS_UPDATE environment variable

- changes/455.removal.rst
- src/stdatamodels/model_base.py
- tests/test_fits.py
- tests/test_models.py
This PR deprecates 2 unused class methods on DataModel, `from_fits` and `from_asdf`. Both are unused in jwst and are effectively aliases of `DataModel.__init__`.
Regression tests all pass and show no instances of the DeprecationWarning added in this PR: https://github.com/spacetelescope/RegressionTests/actions/runs/13930838346
</details>
> Deprecate DataModel.from_fits and DataModel.from_asdf

- src/stdatamodels/jwst/datamodels/tests/test_schema_against_crds.py
The new jwst context https://jwst-crds.stsci.edu/context_table/jwst_1361.pmap contains a new `bkg` reftype which does not have a corresponding datamodel. At the moment all new `bkg` are `WFSS` so we can use `WfssBkgModel`.
This is causing test failures on main: https://github.com/spacetelescope/stdatamodels/actions/runs/14044807882
This PR updates the schema/crds test to use `WfssBkgModel` for the `bkg` reftype.
</details>
> Set bkg reftype check to use WfssBkgModel

- changes/461.bugfix.rst
- src/stdatamodels/jwst/datamodels/util.py
- src/stdatamodels/model_base.py
This removes file-less AsdfFile instances from tracked file references for DataModels. It addresses an issue where exiting an interactive python 3.13 session with an open model results in a `TypeError`:
```
TypeError: 'NoneType' object is not callable
```
Code to replicate the issue is:
```python
from jwst import datamodels
a = datamodels.ImageModel()
```
However given the odd set of circumstances to trigger the exception (which does not result in a non-0 exit code) no unit test is added in this PR as I can't think of a way to trigger this in the CI.
regtests all pass: https://github.com/spacetelescope/RegressionTests/actions/runs/14338332360
- ``changes/<PR#>.bugfix.rst``: fixes an …
> don't track file reference to fileless AsdfFile

- changes/469.feature.rst
- src/stdatamodels/properties.py
- tests/models.py
- tests/schemas/table_model.yaml
- tests/schemas/table_model_bad_defaults.yaml
- tests/test_models.py
Relates to [JP-3931](https://jira.stsci.edu/browse/JP-3931)
Closes #468 
This PR allows multi-valued defaults to be passed in for table-like schemas.
</details>
> Add support for multi-valued defaults in recarray-like schemas

- changes/476.bugfix.rst
- src/stdatamodels/jwst/datamodels/tests/test_read_metadata.py
- src/stdatamodels/jwst/datamodels/util.py
Closes #475 
This PR fixes a bug that the initial implementation of `_to_flat_dict` failed to handle nested lists.
That was causing the failures discussed on the issue thanks to our favorite piece of stdatamodels, `extra_fits`, which apparently represents headers as nested lists.  The fact that this only occurred inside `extra_fits` was one reason we didn't catch this initially.
</details>
> Refactor to_flat_dict to handle nested lists

- changes/483.feature.rst
- pyproject.toml
- src/stdatamodels/jwst/transforms/extensions.py
- src/stdatamodels/jwst/transforms/resources/manifests/jwst_transforms-1.2.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/coords-1.2.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/grating_equation-1.2.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/gwa_to_slit-1.2.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/logical-1.2.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/miri_ab2slice-1.2.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/nircam_grism_dispersion-1.2.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/niriss_grism_dispersion-1.2.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/niriss_soss-1.2.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/refraction_index_from_prism-1.2.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/rotation_sequence-1.2.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/slit_to_msa-1.2.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/snell-1.2.0.yaml
This PR updates the transform schemas to use the new transform-1.4.0 schema in asdf-transform-schemas.
Regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/15194045401
</details>
> bump transform-1.3.0 to 1.4.0

- changes/465.feature.rst
- src/stdatamodels/jwst/transforms/converters/jwst_models.py
- src/stdatamodels/jwst/transforms/extensions.py
- src/stdatamodels/jwst/transforms/models.py
- src/stdatamodels/jwst/transforms/resources/manifests/jwst_transforms-1.1.0.yaml
- src/stdatamodels/jwst/transforms/resources/manifests/jwst_transforms-1.2.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/msa_to_slit-1.0.0.yaml
- src/stdatamodels/jwst/transforms/resources/schemas/stsci.edu/jwst_pipeline/slit_to_gwa-1.0.0.yaml
- src/stdatamodels/jwst/transforms/tests/test_transforms.py
- src/stdatamodels/jwst/transforms/tests/tests.py
Resolves [JP-1028](https://jira.stsci.edu/browse/JP-1028)
Requires https://github.com/spacetelescope/jwst/pull/9404
Update NIRSpec WCS transforms to propagate the slit name throughout.
Changes include:
- Inverse transforms for Slit2Msa and Gwa2Slit
- Change outputs for Slit2Msa to include slit name
- Add a legacy model to handle old output structure for Slit2Msa
- Add a slit ID to the Slit tuple, to allow NIRSpec FS slits to be uniquely identified with a numerical value (slit.name is a string, which can't be passed through the WCS transforms).
- ``changes/<PR#>.removal.rst``: deprecation or …
> JP-1028: Propagate slit name through NIRSpec WCS

- changes/487.removal.rst
- src/stdatamodels/filetype.py
- src/stdatamodels/jwst/datamodels/tests/test_open.py
- src/stdatamodels/jwst/datamodels/util.py
- src/stdatamodels/model_base.py
- tests/test_filetype.py
Closes #423 
This PR addresses the above-linked issue by making `filetype.check()` accept `Path` as input, and removing handling of `BytesIO` type.
It was discovered that reading datamodels from a `BytesIO` or `bytes`  representation already does not work on main.  This PR removes all code that attempted to handle that case.
This PR also changes an instance of `ValueError` to `TypeError` in `DataModel.__init__()`.  This is probably a slightly risky change and it's important to be careful with it.  (I could also be convinced to revert this if reviewers dislike it.)
- …
> Remove code that attempts to handle opening datamodels from buffer

- changes/484.feature.rst
- src/stdatamodels/jwst/datamodels/photom.py
- src/stdatamodels/jwst/datamodels/schemas/nrcimg_photom.schema.yaml
Resolves [JP-3837](https://jira.stsci.edu/browse/JP-3837)
NIRCam wants to allow matching by subarray to the photom table rows, for the imaging modes.  To allow both old and new files to work in the transition, I am updating the schema to allow extra columns in the reference file, rather than defining the subarray column specifically.  In future builds, this can be cleaned up to require the subarray column if desired.
</details>
> JP-3837: Allow extra columns in NrcImgPhotomModel phot_table

- changes/479.feature.rst
- src/stdatamodels/jwst/datamodels/schemas/ifuimage.schema.yaml
Resolves [JP-3922](https://jira.stsci.edu/browse/JP-3922)
Add a new data array to IFUImageModel, to hold a pixel to slice map.  This is intended for NRS IFU data, for which there is no static regions reference file.
</details>
> JP-3922: Add a regions array to NRS IFU models

- changes/513.bugfix.rst
- src/stdatamodels/jwst/datamodels/schemas/specpsf.schema.yaml
- src/stdatamodels/jwst/datamodels/tests/test_schema_against_crds.py
CRDS context 1406 https://jwst-crds.stsci.edu/context_table/jwst_1406.pmap
has some updates that are causing test failures:
https://github.com/spacetelescope/stdatamodels/actions/runs/15968561775
The relevant changes are:
- miri psf reference files now using band and channel selectors (these keywords are added to the specpsf schema in this PR)
- a new NRC_WFSS exptype background (this exptype added to the bkg_model_map in this PR)
</details>
> Update for crds 1406

- changes/519.bugfix.rst
- pyproject.toml
- src/stdatamodels/jwst/transforms/models.py
- src/stdatamodels/jwst/transforms/tests/test_transforms.py
Closes #388 
Closes #517 
This PR:
- Adds unit test coverage for the transforms in `jwst/transforms/models.py`.
- Improves the way that sampling the trace function is handled by WFSS transforms, including a bugfix for #517 
- Drops partial support for NIRCam models that have trace functions x(t), y(t) whose coefficients are 1st order polynomials in (x0, y0).  These are supported in the forward transform but fail to round-trip on main due to being unsupported by the backward transform.
- Adds scipy as a testing dependency, which is required for the use of certain Astropy models.
This PR is a prerequisite to handling #389 #390 and #520 
- …
> Unit tests and small bugfixes for transform models

- src/stdatamodels/jwst/transforms/models.py
- src/stdatamodels/jwst/transforms/tests/test_transforms.py
Closes #389 
This PR allows for the removal of some `noqa: TRY002` tags by removing the use of bare `Except`.
</details>
> Change bare Except to ValueError in grism dispersion models

- .github/workflows/ci.yml
Upload coverage report from jwst downstream tests.
Coverage ran and uploaded: https://github.com/spacetelescope/stdatamodels/actions/runs/16523091654/job/46729427115?pr=534#step:13:323
</details>
> upload coverage from jwst run

- changes/533.misc.rst
- changes/533.removal.rst
- src/stdatamodels/asdf_in_fits.py
- src/stdatamodels/fits_support.py
- src/stdatamodels/jwst/datamodels/util.py
- src/stdatamodels/model_base.py
- tests/test_asdf_in_fits.py
Closes #239 
Partially addresses #398 
This PR addresses a few related issues with kwargs handling in datamodel init and `asdf_in_fits.open`:
- Document array assignment during `DataModel.__init__`
- Make array assignment the only usage of `**kwargs` in `DataModel.__init__`
- Remove `**kwargs` in `asdf_in_fits.open`, `from_fits`, and `from_fits_asdf`, making `ignore_unrecognized_tag` and `ignore_missing_extensions` into args instead
</details>
> Update handling of kwargs in datamodel init and asdf_in_fits.open

- changes/552.misc.rst
- src/stdatamodels/model_base.py
- tests/test_resources.py
Closes #300 
This PR makes it so that that when a model is initialized or opened from .fits, the `hdulist` is closed during `DataModel.__init__` instead of being left open until datamodel close.
There is no good reason to keep the hdulist around, since converting the hdulist to asdf handles all fits-related quirks during init anyway.
Regression tests show that there are no pipeline failures, and that the memory usage of many pipelines is modestly but nontrivially lower with these changes for many of the memory-tracked tests: https://github.com/spacetelescope/RegressionTests/actions/runs/16886681733
- ``changes/<PR#>.doc.rst``: documentation …
> Close hdulist during datamodel init and remove from file references

- src/stdatamodels/jwst/datamodels/util.py
- src/stdatamodels/model_base.py
Resolves [JP-4045](https://jira.stsci.edu/browse/JP-4045)
Closes https://github.com/spacetelescope/jwst/issues/9589
This PR adds documentation of what happens when an already-open datamodel is opened.
</details>
> Add docstrings for opening or initializing from an already-open datamodel

- changes/550.removal.rst
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
This PR is a companion of
* https://github.com/spacetelescope/jwst/pull/9486
as requested by @melanieclarke in https://github.com/spacetelescope/jwst/pull/9486#issuecomment-3165662951
</details>
> Removed mrs_imatch from cal_step status

- changes/579.feature.rst
- src/stdatamodels/jwst/datamodels/model_base.py
- src/stdatamodels/jwst/datamodels/tests/test_models.py
Resolves [JP-4077](https://jira.stsci.edu/browse/JP-4077)
When new models are created within the pipeline (e.g. resampling), any previous log messages recorded in `cal_logs` are lost.  In order to preserve them, this PR adds `cal_logs` handling to the update method for JwstDataModels.  When metadata is copied from the input models to the new model, the log messages will be copied too.
</details>
> JP-4077: Add cal_logs to JwstDataModel update handling

- pyproject.toml
Enables `release-branch-semver` option for setuptools_scm to allow picking up named release branches when determining the dev version.
See https://setuptools-scm.readthedocs.io/en/latest/config/ for documentation.
All credit to @tapastro for finding this option.
We will want to drop the 4.1.0.dev tag on main before we merge this PR (with this setting and that tag the version will be 4.2.0.dev..., without that tag the version will be 4.1.0.dev...). …
> enable release-branch-semver setuptools_scm configuration

- changes/594.bugfix.rst
- src/stdatamodels/jwst/datamodels/schemas/mask.schema.yaml
- src/stdatamodels/jwst/datamodels/tests/test_schema_against_crds.py
The tests against crds test is failing on main with the new crds context:
https://github.com/spacetelescope/stdatamodels/actions/runs/18160115109/job/51688850979
https://jwst-crds.stsci.edu/context_table/jwst_1460.pmap
It is failing due to `MIR_WFSS` not being listed here:
https://github.com/spacetelescope/stdatamodels/blob/47a0d86770e90aa9ed8fee84767de64c3a34ab15/src/stdatamodels/jwst/datamodels/tests/test_schema_against_crds.py#L67-L71
and due to `filter` not being listed in the `mask` schema.
This PR adds `filter` to the `mask` schema and assigns the `WfssBkgModel` for `MIR_WFSS` to fix the two failures.
Regtests: https://github.com/spacetelescope/RegressionTests/actions/runs/18160951926
Failures look unrelated and due to some MAST/EngDB outage/change.
<details><summary>news fragment …
> add filter to mask model, add BkgModel for MIR_WFSS
