- src/stdatamodels/fits_support.py
- src/stdatamodels/util.py
- tests/test_fits.py
- tests/test_util.py
This PR adds test coverage of util.py.
> Add test coverage of util module

- tests/test_filetype.py
- tests/test_s3_utils.py
... and one little assertion missing from test_s3_utils.py.
> Improve test coverage of filetype.py

- tests/schemas/core_metadata.yaml
- tests/schemas/fits_model.yaml
- tests/test_fits.py
This went pretty smoothly in the end.  I didn't make any attempt to improve the tests, just coaxed the relevant specimens into passing.  We can take another pass at cleaning them up once we know how we're going forward with tags or not-tags.
> Update tests in test_fits.py

- .github/workflows/ci.yml
- tox.ini
> Remove romancal.datamodels tests from test suite

- src/stdatamodels/model_base.py
> Remove DataModel.my_attribute from public interface

- .github/workflows/ci.yml
> Do apt update before doc dependencies install in CI

- tests/test_validation.py
Just fixing some warnings that cropped up due to a pytest deprecation...
> Resolve deprecation warnings due to use of pytest.warns(None)

- .github/workflows/ci.yml
- tox.ini
fix for CRDS issue in downstream CI tests (not required by `0.4.5` release)
**Checklist**
> cache CRDS by context

- .readthedocs.yaml
- pyproject.toml
This PR updates the RTD configuration and installs `tomli` on versions less than Python 3.11
**Checklist**
> update RTD build

- pyproject.toml
This PR addresses issues with testing that arise from upper pins on dependencies.
**Checklist**
> remove upper pins on dependencies

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
Resolves [JP-3099](https://jira.stsci.edu/browse/JP-3099)
Closes #
This PR added the reference information for the mrsxartcorr to the core schema. The reference file used in the straylight step is now written to the header. 
**Checklist**
> JP-3099 addded mrsxartcorr to core.schema

- .github/workflows/ci.yml
- tox.ini
This PR consolidates and simplifies the CI workflow.
**Checklist**
> consolidate test and check jobs

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/__init__.py
- src/stdatamodels/jwst/datamodels/outlierifuoutput.py
- src/stdatamodels/jwst/datamodels/schemas/outlierifuoutput.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/outlierpars.schema.yaml
Partially resolves [JP-3207](https://jira.stsci.edu/browse/JP-3207)
This PR updates the outlierpars schema to include two new parameters (stored in table columns) needed for a new JWST IFU outlier detection algorithm. In addition, to support analysis of the new algorithm for IFU data, an optional output outliers data model has been created. If save_intermediate_results is True, then additional data using this new data model is written to disk.  
**Checklist**
> Update of outlierpars file for IFU outlier detection 

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/photom.py
- src/stdatamodels/jwst/datamodels/schemas/mirmrs_photom.schema.yaml
Partially Resolves [JP-3224](https://jira.stsci.edu/browse/JP-3224)
Closes #
This PR updates the JWST/MIRI MRS photom reference file to read in the time dependent corrections. 
**Checklist**
>  update to JWST/MIRI MRS photom data model

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
Resolves [JP-3302](https://jira.stsci.edu/browse/JP-3302)
Closes https://github.com/spacetelescope/jwst/issues/7710
This PR adds definitions for the 2 new JWST keywords "TARGCAT" and "TARGDESC" to the core schema.
**Checklist**
> JP-3302: Add TARGCAT and TARGDESC keywords

- .github/workflows/ci.yml
> add workflow_dispatch to ci.yml

- CHANGES.rst
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
This PR is needed to resolves [JP-3327](https://jira.stsci.edu/browse/JP-3327)
Closes #
This PR addresses adds the ref_file mrsptcorr to code file. This reference file is the MRS Point Source Correction reference file. This reference file is needed for JP-3327. 
**Checklist**
> Added mrsptcorr ref file information to core.schema to support JP-3327

- src/stdatamodels/jwst/datamodels/tests/test_fits.py
Resolves [JP-1048](https://jira.stsci.edu/browse/JP-1048)
No associated GitHub issue
This PR adds a simple unit test covering a long-since-fixed bug wherein the `dq_def` array was being corrupted after saving and re-loadong a `FlatModel` with `datamodels.save()` and `datamodels.open()`
**Checklist**
> JP-1048: added unit test for dq_def roundtrip

- changes/407.feature.rst
- src/stdatamodels/jwst/datamodels/schemas/core.schema.yaml
Partially Resolves [JP-3808](https://jira.stsci.edu/browse/JP-3808)
This PR adds the background scaling factor to the datamodel schema per request from INS.
</details>
> JP-3808: Add background scaling factor to schema

- .github/workflows/ci.yml
- changes/418.misc.rst
Resolves [SCSB-195](https://jira.stsci.edu/browse/SCSB-195)
</details>
> test with latest supported Python version

- changes/477.feature.rst
- src/stdatamodels/jwst/datamodels/__init__.py
- src/stdatamodels/jwst/datamodels/multispec.py
- src/stdatamodels/jwst/datamodels/schemas/mrs_spec.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/mrs_spectable.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/spec.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/specmeta.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/spectable.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/tso_multispec.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/tso_spec.schema.yaml
- src/stdatamodels/jwst/datamodels/schemas/tso_spectable.schema.yaml
- src/stdatamodels/jwst/datamodels/spec.py
Resolves [JP-3841](https://jira.stsci.edu/browse/JP-3841)
Add a new spectral model for TSO data, to hold a flat table containing all integrations in a single FITS extension.
New models are used in https://github.com/spacetelescope/jwst/pull/9430
</details>
> JP-3841: Flat spectral table for TSO

- README.md
I noticed the badges were broken. This PR repairs those broken badges
</details>
> Fix the broken badges
